// 全局检查通知只跟踪真实Run，终态和完整性分开，不触发导航或提交。
import { act, renderHook, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import type { CheckStatus } from '../../api/checks/currentChecks'
import { useCheckActivity } from './useCheckActivity'
const api = vi.hoisted(() => ({ status: vi.fn(), submit: vi.fn() }))
vi.mock('../../api/checks/currentChecks', () => ({ currentChecksApi: api }))
const active: CheckStatus = { run: { project_id: 'p1', run_id: 'r1', lifecycle: 'RUNNING', verdict: null, plan_fingerprint: 'x', policy_epoch: 1, created_at_us: 1, finished_at_us: null }, progress: null, job: null, result_integrity: 'NOT_PUBLISHED' }
beforeEach(() => { vi.clearAllMocks() })
afterEach(() => vi.useRealTimers())
it.each(['PASS','BLOCK','INCONCLUSIVE'] as const)('关闭进度后仍轮询，%s 完成通知独立出现',async verdict=>{
  vi.useFakeTimers();api.status.mockResolvedValue(active)
  const refresh=vi.fn().mockResolvedValue(undefined)
  const view=renderHook(()=>useCheckActivity('p1',active,refresh))
  await act(async()=>{await vi.advanceTimersByTimeAsync(0)})
  act(()=>view.result.current.dismissProgress())
  expect(view.result.current.progressDismissed).toBe(true)
  expect(view.result.current.activeRunId).toBe('r1')
  await act(async()=>{await vi.advanceTimersByTimeAsync(2000)})
  expect(api.status).toHaveBeenCalledTimes(2)
  expect(view.result.current.progressDismissed).toBe(true)
  api.status.mockResolvedValue({...active,run:{...active.run,lifecycle:'COMPLETED',verdict},result_integrity:'VALID'})
  await act(async()=>{await vi.advanceTimersByTimeAsync(2000)})
  expect(view.result.current.completed?.runId).toBe('r1')
  expect(view.result.current.activeRunId).toBeUndefined()
  expect(refresh).toHaveBeenCalledOnce();expect(api.submit).not.toHaveBeenCalled()
  view.unmount()
})
it('关闭进度只作用于当前项目和本次检查',async()=>{
  vi.useFakeTimers();api.status.mockResolvedValue(active)
  const view=renderHook(({project,value})=>useCheckActivity(project,value,vi.fn()),{initialProps:{project:'p1',value:active}})
  await act(async()=>{await vi.advanceTimersByTimeAsync(0)})
  act(()=>view.result.current.dismissProgress())
  const next={...active,run:{...active.run,run_id:'r2'}}
  api.status.mockResolvedValue(next);view.rerender({project:'p1',value:next})
  expect(view.result.current.progressDismissed).toBe(false)
  act(()=>view.result.current.dismissProgress())
  const other={...next,run:{...next.run,project_id:'p2'}}
  api.status.mockResolvedValue(other);view.rerender({project:'p2',value:other})
  await act(async()=>{await vi.advanceTimersByTimeAsync(0)})
  expect(view.result.current.progressDismissed).toBe(false)
  view.unmount()
})
it('长检查超过五分钟仍跟踪并在临时断连后自动完成',async()=>{
  vi.useFakeTimers();api.status.mockResolvedValue(active)
  const refresh=vi.fn().mockResolvedValue(undefined)
  const view=renderHook(()=>useCheckActivity('p1',active,refresh))
  await act(async()=>{await vi.advanceTimersByTimeAsync(310000)})
  expect(api.status.mock.calls.length).toBeGreaterThan(150)
  api.status.mockRejectedValueOnce(new Error('temporary'))
  await act(async()=>{await vi.advanceTimersByTimeAsync(2000)})
  expect(view.result.current.paused).toBe(true)
  api.status.mockResolvedValue({...active,run:{...active.run,lifecycle:'COMPLETED',verdict:'BLOCK'},result_integrity:'VALID'})
  await act(async()=>{await vi.advanceTimersByTimeAsync(4000)})
  expect(view.result.current.completed?.label).toBe('检查完成，发现权限问题')
  expect(api.submit).not.toHaveBeenCalled();view.unmount()
})
it('不通知首次恢复的旧结果，但补获轮询间隙已经结束的新检查', async () => {
  api.status.mockResolvedValue({...active,run:{...active.run,run_id:'r2',lifecycle:'COMPLETED',verdict:'PASS'},result_integrity:'VALID'})
  const refresh=vi.fn()
  const view=renderHook(({latest})=>useCheckActivity('p1',null,refresh,latest,true),{initialProps:{latest:'r1'}})
  expect(api.status).not.toHaveBeenCalled()
  view.rerender({latest:'r2'})
  await waitFor(()=>expect(view.result.current.completed?.runId).toBe('r2'))
  expect(api.status).toHaveBeenCalledWith('r2');expect(api.submit).not.toHaveBeenCalled()
})
it('完整性未通过时不把持久PASS用作完成通知', async () => {
  api.status.mockResolvedValue({ ...active, run: { ...active.run, lifecycle: 'COMPLETED', verdict: 'PASS' }, result_integrity: 'INVALID' })
  const refresh = vi.fn().mockResolvedValue(undefined); const { result } = renderHook(() => useCheckActivity('p1', active, refresh))
  await waitFor(() => expect(result.current.completed?.label).toBe('检查已结束，结果完整性校验失败'))
  expect(refresh).toHaveBeenCalledTimes(1); expect(api.submit).not.toHaveBeenCalled()
  act(() => result.current.dismiss()); expect(result.current.completed).toBeNull()
})
it('只读失败保留同步暂停状态，不重试副作用', async () => {
  api.status.mockRejectedValue(new Error('read unavailable'))
  const refresh = vi.fn(); const { result } = renderHook(() => useCheckActivity('p1', active, refresh))
  await waitFor(() => expect(result.current.paused).toBe(true))
  expect(result.current.completed).toBeNull(); expect(api.status).toHaveBeenCalledTimes(1); expect(refresh).not.toHaveBeenCalled()
})
it('卸载后迟到的终态不通知新页面', async () => {
  let finish!: (status: CheckStatus) => void
  api.status.mockImplementation(() => new Promise(resolve => { finish = resolve }))
  const refresh = vi.fn(); const view = renderHook(() => useCheckActivity('p1', active, refresh))
  view.unmount()
  await act(async () => finish({ ...active, run: { ...active.run, lifecycle: 'COMPLETED', verdict: 'PASS' }, result_integrity: 'VALID' }))
  expect(refresh).not.toHaveBeenCalled()
})

it('关闭终态通知后不再显示旧进度，新检查仍能跟踪', async()=>{
 api.status.mockResolvedValue({...active,run:{...active.run,lifecycle:'COMPLETED',verdict:'PASS'},result_integrity:'VALID'})
 const refresh=vi.fn(),view=renderHook(({value})=>useCheckActivity('p1',value,refresh),{initialProps:{value:active}})
 await waitFor(()=>expect(view.result.current.completed?.runId).toBe('r1'))
 act(()=>view.result.current.dismiss());expect(view.result.current.completed).toBeNull();expect(view.result.current.activeRunId).toBeUndefined()
 const next={...active,run:{...active.run,run_id:'r2'}};api.status.mockResolvedValue(next);view.rerender({value:next})
 await waitFor(()=>expect(api.status).toHaveBeenLastCalledWith('r2'));expect(view.result.current.activeRunId).toBe('r2')
 view.unmount()
})
