"""Current database baseline. Existing development databases are intentionally incompatible.

This migration is self-contained and mirrors the current storage metadata.
"""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('llm_profiles',
        sa.Column('profile_name', sa.String(length=128), nullable=False),
        sa.Column('schema_version', sa.String(length=8), nullable=False),
        sa.Column('provider', sa.String(length=32), nullable=False),
        sa.Column('model', sa.String(length=256), nullable=False),
        sa.Column('base_url', sa.String(length=2048), nullable=True),
        sa.Column('timeout_ms', sa.Integer(), nullable=False),
        sa.Column('max_input_bytes', sa.Integer(), nullable=False),
        sa.Column('max_output_bytes', sa.Integer(), nullable=False),
        sa.Column('max_budget_microusd', sa.BigInteger(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('secret_ref', sa.String(length=256), nullable=True),
        sa.Column('allow_local_http', sa.Boolean(), nullable=False),
        sa.Column('created_at_us', sa.BigInteger(), nullable=False),
        sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
        sa.CheckConstraint("length(profile_name) BETWEEN 1 AND 128 AND substr(profile_name, 1, 1) GLOB '[a-z]' AND profile_name NOT GLOB '*[^a-z0-9_-]*'", name=op.f('ck_llm_profiles_profile_name_format')),
        sa.CheckConstraint("provider IN ('openai', 'deepseek', 'gemini', 'openai_compatible')", name=op.f('ck_llm_profiles_provider_value')),
        sa.CheckConstraint("schema_version = '1'", name=op.f('ck_llm_profiles_schema_version_value')),
        sa.CheckConstraint('base_url IS NULL OR length(base_url) BETWEEN 1 AND 2048', name=op.f('ck_llm_profiles_base_url_length')),
        sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_llm_profiles_time_order')),
        sa.CheckConstraint('length(model) BETWEEN 1 AND 256', name=op.f('ck_llm_profiles_model_length')),
        sa.CheckConstraint('max_budget_microusd BETWEEN 0 AND 1000000000', name=op.f('ck_llm_profiles_budget_range')),
        sa.CheckConstraint('max_input_bytes BETWEEN 1 AND 1048576', name=op.f('ck_llm_profiles_input_bytes_range')),
        sa.CheckConstraint('max_output_bytes BETWEEN 1 AND 1048576', name=op.f('ck_llm_profiles_output_bytes_range')),
        sa.CheckConstraint('secret_ref IS NULL OR length(secret_ref) BETWEEN 1 AND 256', name=op.f('ck_llm_profiles_secret_ref_length')),
        sa.CheckConstraint('timeout_ms BETWEEN 100 AND 300000', name=op.f('ck_llm_profiles_timeout_range')),
        sa.PrimaryKeyConstraint('profile_name', name=op.f('pk_llm_profiles'))
        )
        op.create_table('projects',
        sa.Column('project_id', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('target_type', sa.String(length=32), nullable=False),
        sa.Column('governed_contract_id', sa.String(length=128), nullable=True),
        sa.Column('governed_contract_version', sa.Integer(), nullable=True),
        sa.Column('created_at_us', sa.BigInteger(), nullable=False),
        sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
        sa.CheckConstraint("length(project_id) BETWEEN 1 AND 64 AND substr(project_id, 1, 1) GLOB '[a-z]' AND project_id NOT GLOB '*[^a-z0-9_-]*'", name=op.f('ck_projects_project_id_format')),
        sa.CheckConstraint("status IN ('DRAFT', 'READY', 'ARCHIVED')", name=op.f('ck_projects_status_value')),
        sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_projects_time_order')),
        sa.CheckConstraint('length(name) BETWEEN 1 AND 128', name=op.f('ck_projects_name_length')),
        sa.PrimaryKeyConstraint('project_id', name=op.f('pk_projects'))
        )
        op.create_index('ix_projects_status_updated', 'projects', ['status', 'updated_at_us'], unique=False)
        op.execute(
            "CREATE TRIGGER projects_governed_binding_insert "
            "BEFORE INSERT ON projects BEGIN "
            "SELECT RAISE(ABORT, 'governed contract binding must be paired') "
            "WHERE (NEW.governed_contract_id IS NULL) != (NEW.governed_contract_version IS NULL) "
            "OR (NEW.governed_contract_version IS NOT NULL AND NEW.governed_contract_version < 1); END"
        )
        op.execute(
            "CREATE TRIGGER projects_governed_binding_update "
            "BEFORE UPDATE OF governed_contract_id, governed_contract_version ON projects BEGIN "
            "SELECT RAISE(ABORT, 'governed contract binding must be paired') "
            "WHERE (NEW.governed_contract_id IS NULL) != (NEW.governed_contract_version IS NULL) "
            "OR (NEW.governed_contract_version IS NOT NULL AND NEW.governed_contract_version < 1); END"
        )
        op.create_table('contract_candidates',
        sa.Column('candidate_id', sa.String(length=37), nullable=False),
        sa.Column('schema_version', sa.String(length=8), nullable=False),
        sa.Column('project_id', sa.String(length=64), nullable=False),
        sa.Column('source_type', sa.String(length=32), nullable=False),
        sa.Column('source_locator', sa.String(length=1024), nullable=False),
        sa.Column('source_sha256', sa.String(length=64), nullable=False),
        sa.Column('rule_json', sa.Text(), nullable=False),
        sa.Column('requirement_ids_json', sa.Text(), nullable=False),
        sa.Column('llm_metadata_json', sa.Text(), nullable=True),
        sa.Column('created_by', sa.String(length=128), nullable=False),
        sa.Column('created_at_us', sa.BigInteger(), nullable=False),
        sa.CheckConstraint("length(candidate_id) = 37 AND substr(candidate_id, 1, 5) = 'cand_' AND substr(candidate_id, 6) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_contract_candidates_candidate_id_format')),
        sa.CheckConstraint("length(source_sha256) = 64 AND source_sha256 NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_contract_candidates_source_sha256_format')),
        sa.CheckConstraint("schema_version = '1'", name=op.f('ck_contract_candidates_schema_version_value')),
        sa.CheckConstraint("source_type IN ('requirement_text', 'project_config', 'recording_flow', 'static_analysis', 'llm')", name=op.f('ck_contract_candidates_source_type_value')),
        sa.CheckConstraint('created_at_us >= 0', name=op.f('ck_contract_candidates_created_nonnegative')),
        sa.CheckConstraint('length(created_by) BETWEEN 1 AND 128', name=op.f('ck_contract_candidates_created_by_length')),
        sa.CheckConstraint('length(requirement_ids_json) BETWEEN 2 AND 65536', name=op.f('ck_contract_candidates_requirement_ids_json_length')),
        sa.CheckConstraint('length(rule_json) BETWEEN 2 AND 65536', name=op.f('ck_contract_candidates_rule_json_length')),
        sa.CheckConstraint('length(source_locator) BETWEEN 1 AND 1024', name=op.f('ck_contract_candidates_source_locator_length')),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_contract_candidates_project_id_projects'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('candidate_id', name=op.f('pk_contract_candidates'))
        )
        op.create_index('ix_contract_candidates_project_created', 'contract_candidates', ['project_id', 'created_at_us'], unique=False)
        op.create_table('contract_versions',
        sa.Column('project_id', sa.String(length=64), nullable=False),
        sa.Column('contract_id', sa.String(length=128), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('schema_version', sa.String(length=8), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('snapshot_json', sa.Text(), nullable=False),
        sa.Column('provenance_json', sa.Text(), nullable=False),
        sa.Column('supersedes_version', sa.Integer(), nullable=True),
        sa.Column('audit_json', sa.Text(), nullable=False),
        sa.Column('created_at_us', sa.BigInteger(), nullable=False),
        sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
        sa.CheckConstraint("schema_version = '1'", name=op.f('ck_contract_versions_schema_version_value')),
        sa.CheckConstraint("status IN ('DRAFT', 'REVIEW', 'ACTIVE', 'SUPERSEDED', 'REJECTED')", name=op.f('ck_contract_versions_status_value')),
        sa.CheckConstraint('(version = 1 AND supersedes_version IS NULL) OR (version > 1 AND supersedes_version = version - 1)', name=op.f('ck_contract_versions_supersedes_version_order')),
        sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_contract_versions_time_order')),
        sa.CheckConstraint('length(audit_json) BETWEEN 2 AND 131072', name=op.f('ck_contract_versions_audit_json_length')),
        sa.CheckConstraint('length(contract_id) BETWEEN 1 AND 128', name=op.f('ck_contract_versions_contract_id_length')),
        sa.CheckConstraint('length(provenance_json) BETWEEN 2 AND 1048576', name=op.f('ck_contract_versions_provenance_json_length')),
        sa.CheckConstraint('length(snapshot_json) BETWEEN 2 AND 1048576', name=op.f('ck_contract_versions_snapshot_json_length')),
        sa.CheckConstraint('version >= 1', name=op.f('ck_contract_versions_version_positive')),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_contract_versions_project_id_projects'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('project_id', 'contract_id', 'version', name=op.f('pk_contract_versions'))
        )
        op.create_index('ix_contract_versions_project_status', 'contract_versions', ['project_id', 'status', 'updated_at_us'], unique=False)
        op.create_index('uq_contract_versions_active', 'contract_versions', ['project_id', 'contract_id'], unique=True, sqlite_where=sa.text("status = 'ACTIVE'"))
        op.create_table('execution_profiles',
        sa.Column('profile_id', sa.String(length=64), nullable=False),
        sa.Column('schema_version', sa.String(length=8), nullable=False),
        sa.Column('project_id', sa.String(length=64), nullable=False),
        sa.Column('source_path', sa.String(length=2048), nullable=False),
        sa.Column('source_hash', sa.String(length=64), nullable=False),
        sa.Column('contract_id', sa.String(length=128), nullable=False),
        sa.Column('contract_version', sa.Integer(), nullable=False),
        sa.Column('contract_fingerprint', sa.String(length=64), nullable=False),
        sa.Column('plan_fingerprint', sa.String(length=64), nullable=False),
        sa.Column('engine_version', sa.String(length=128), nullable=False),
        sa.Column('created_at_us', sa.BigInteger(), nullable=False),
        sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
        sa.CheckConstraint("length(profile_id) BETWEEN 1 AND 64 AND substr(profile_id, 1, 1) GLOB '[a-z]' AND profile_id NOT GLOB '*[^a-z0-9_-]*'", name=op.f('ck_execution_profiles_profile_id_format')),
        sa.CheckConstraint("schema_version = '2'", name=op.f('ck_execution_profiles_profile_schema_version_value')),
        sa.CheckConstraint('contract_version >= 1', name=op.f('ck_execution_profiles_profile_contract_version')),
        sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_execution_profiles_profile_time_order')),
        sa.CheckConstraint('length(source_hash) = 64 AND length(contract_fingerprint) = 64 AND length(plan_fingerprint) = 64', name=op.f('ck_execution_profiles_profile_hash_lengths')),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_execution_profiles_project_id_projects')),
        sa.PrimaryKeyConstraint('profile_id', name=op.f('pk_execution_profiles'))
        )
        op.create_index('ix_permission_profiles_project_updated', 'execution_profiles', ['project_id', 'updated_at_us'], unique=False)
        op.create_table('findings',
        sa.Column('finding_id', sa.String(length=40), nullable=False),
        sa.Column('schema_version', sa.String(length=8), nullable=False),
        sa.Column('project_id', sa.String(length=64), nullable=False),
        sa.Column('identity_json', sa.Text(), nullable=False),
        sa.Column('created_at_us', sa.BigInteger(), nullable=False),
        sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
        sa.CheckConstraint("length(finding_id) = 40 AND substr(finding_id, 1, 8) = 'finding_' AND substr(finding_id, 9) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_findings_finding_id_format')),
        sa.CheckConstraint("schema_version = '1'", name=op.f('ck_findings_finding_schema_version_value')),
        sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_findings_finding_time_order')),
        sa.CheckConstraint('length(identity_json) BETWEEN 1 AND 16384', name=op.f('ck_findings_finding_identity_length')),
        sa.CheckConstraint('length(project_id) BETWEEN 1 AND 64', name=op.f('ck_findings_finding_project_id_length')),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_findings_project_id_projects'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('finding_id', name=op.f('pk_findings'))
        )
        op.create_index('ix_findings_project_updated', 'findings', ['project_id', 'updated_at_us'], unique=False)
        op.create_table('recordings',
        sa.Column('recording_id', sa.String(length=36), nullable=False),
        sa.Column('project_id', sa.String(length=64), nullable=False),
        sa.Column('flow_id', sa.String(length=64), nullable=False),
        sa.Column('state', sa.String(length=32), nullable=False),
        sa.Column('created_at_us', sa.BigInteger(), nullable=False),
        sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
        sa.Column('started_at_us', sa.BigInteger(), nullable=True),
        sa.Column('capture_finished_at_us', sa.BigInteger(), nullable=True),
        sa.Column('finished_at_us', sa.BigInteger(), nullable=True),
        sa.Column('pending_terminal_state', sa.String(length=24), nullable=True),
        sa.Column('reason_codes_json', sa.Text(), nullable=False),
        sa.Column('state_events_json', sa.Text(), nullable=False),
        sa.Column('browser_events_json', sa.Text(), nullable=False),
        sa.CheckConstraint("(state IN ('COMPLETED', 'FAILED', 'CANCELLED', 'SAFETY_STOPPED') AND finished_at_us IS NOT NULL) OR (state NOT IN ('COMPLETED', 'FAILED', 'CANCELLED', 'SAFETY_STOPPED') AND finished_at_us IS NULL)", name=op.f('ck_recordings_terminal_finish_matrix')),
        sa.CheckConstraint("length(flow_id) BETWEEN 1 AND 64 AND substr(flow_id, 1, 1) GLOB '[a-z]' AND flow_id NOT GLOB '*[^a-z0-9_-]*'", name=op.f('ck_recordings_flow_id_format')),
        sa.CheckConstraint("length(recording_id) = 36 AND substr(recording_id, 1, 4) = 'rec_' AND substr(recording_id, 5) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_recordings_recording_id_format')),
        sa.CheckConstraint("pending_terminal_state IS NULL OR pending_terminal_state IN ('FAILED', 'CANCELLED', 'SAFETY_STOPPED')", name=op.f('ck_recordings_pending_terminal_state_value')),
        sa.CheckConstraint("state IN ('CREATED', 'STARTING', 'RECORDING', 'CLEANING', 'PROCESSING', 'PENDING_REVIEW', 'COMPLETED', 'FAILED', 'CANCELLED', 'SAFETY_STOPPED')", name=op.f('ck_recordings_state_value')),
        sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us AND (started_at_us IS NULL OR started_at_us >= created_at_us) AND (capture_finished_at_us IS NULL OR capture_finished_at_us >= started_at_us) AND (finished_at_us IS NULL OR finished_at_us >= updated_at_us)', name=op.f('ck_recordings_time_order')),
        sa.CheckConstraint('length(reason_codes_json) BETWEEN 2 AND 8192 AND length(state_events_json) BETWEEN 2 AND 131072 AND length(browser_events_json) BETWEEN 2 AND 4194304', name=op.f('ck_recordings_json_size_bounds')),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_recordings_project_id_projects'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('recording_id', name=op.f('pk_recordings'))
        )
        op.create_index('ix_recordings_project_created', 'recordings', ['project_id', 'created_at_us'], unique=False)
        op.create_index('ix_recordings_state_updated', 'recordings', ['state', 'updated_at_us'], unique=False)
        op.create_table('requirements',
        sa.Column('requirement_id', sa.String(length=36), nullable=False),
        sa.Column('schema_version', sa.String(length=8), nullable=False),
        sa.Column('project_id', sa.String(length=64), nullable=False),
        sa.Column('source_type', sa.String(length=32), nullable=False),
        sa.Column('source_locator', sa.String(length=1024), nullable=False),
        sa.Column('source_sha256', sa.String(length=64), nullable=False),
        sa.Column('requirement_text', sa.Text(), nullable=False),
        sa.Column('security_tags_json', sa.Text(), nullable=False),
        sa.Column('created_by', sa.String(length=128), nullable=False),
        sa.Column('created_at_us', sa.BigInteger(), nullable=False),
        sa.CheckConstraint("length(requirement_id) = 36 AND substr(requirement_id, 1, 4) = 'req_' AND substr(requirement_id, 5) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_requirements_requirement_id_format')),
        sa.CheckConstraint("length(source_sha256) = 64 AND source_sha256 NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_requirements_source_sha256_format')),
        sa.CheckConstraint("schema_version = '1'", name=op.f('ck_requirements_schema_version_value')),
        sa.CheckConstraint("source_type IN ('requirement_text', 'project_config', 'recording_flow', 'static_analysis', 'llm')", name=op.f('ck_requirements_source_type_value')),
        sa.CheckConstraint('created_at_us >= 0', name=op.f('ck_requirements_created_nonnegative')),
        sa.CheckConstraint('length(created_by) BETWEEN 1 AND 128', name=op.f('ck_requirements_created_by_length')),
        sa.CheckConstraint('length(requirement_text) BETWEEN 1 AND 16384', name=op.f('ck_requirements_text_length')),
        sa.CheckConstraint('length(security_tags_json) BETWEEN 2 AND 8192', name=op.f('ck_requirements_tags_json_length')),
        sa.CheckConstraint('length(source_locator) BETWEEN 1 AND 1024', name=op.f('ck_requirements_source_locator_length')),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_requirements_project_id_projects'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('requirement_id', name=op.f('pk_requirements'))
        )
        op.create_index('ix_requirements_project_created', 'requirements', ['project_id', 'created_at_us'], unique=False)
        op.create_table('runs',
        sa.Column('run_id', sa.String(length=36), nullable=False),
        sa.Column('project_id', sa.String(length=64), nullable=False),
        sa.Column('contract_id', sa.String(length=128), nullable=False),
        sa.Column('contract_version', sa.Integer(), nullable=False),
        sa.Column('engine_version', sa.String(length=64), nullable=False),
        sa.Column('lifecycle', sa.String(length=24), nullable=False),
        sa.Column('verdict', sa.String(length=16), nullable=True),
        sa.Column('created_at_us', sa.BigInteger(), nullable=False),
        sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
        sa.Column('finished_at_us', sa.BigInteger(), nullable=True),
        sa.CheckConstraint("(lifecycle = 'COMPLETED' AND verdict IS NOT NULL) OR (lifecycle <> 'COMPLETED' AND verdict IS NULL)", name=op.f('ck_runs_lifecycle_verdict_matrix')),
        sa.CheckConstraint("length(run_id) = 36 AND substr(run_id, 1, 4) = 'run_' AND substr(run_id, 5) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_runs_run_id_format')),
        sa.CheckConstraint("lifecycle IN ('QUEUED', 'PREFLIGHT', 'PLANNING', 'EXECUTING', 'VERIFYING', 'REPORTING', 'COMPLETED', 'FAILED', 'CANCELLED', 'SAFETY_STOPPED')", name=op.f('ck_runs_lifecycle_value')),
        sa.CheckConstraint("verdict IS NULL OR verdict IN ('PASS', 'BLOCK', 'INCONCLUSIVE')", name=op.f('ck_runs_verdict_value')),
        sa.CheckConstraint('contract_version >= 1', name=op.f('ck_runs_contract_version_positive')),
        sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us AND (finished_at_us IS NULL OR finished_at_us >= created_at_us)', name=op.f('ck_runs_time_order')),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_runs_project_id_projects'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('run_id', name=op.f('pk_runs'))
        )
        op.create_index('ix_runs_lifecycle_updated', 'runs', ['lifecycle', 'updated_at_us'], unique=False)
        op.create_index('ix_runs_project_created', 'runs', ['project_id', 'created_at_us'], unique=False)
        op.create_table('evidence_index',
        sa.Column('evidence_id', sa.String(length=67), nullable=False),
        sa.Column('run_id', sa.String(length=36), nullable=False),
        sa.Column('case_id', sa.String(length=128), nullable=False),
        sa.Column('artifact_path', sa.String(length=512, collation='NOCASE'), nullable=False),
        sa.Column('sha256', sa.String(length=64), nullable=False),
        sa.Column('byte_count', sa.BigInteger(), nullable=False),
        sa.Column('created_at_us', sa.BigInteger(), nullable=False),
        sa.CheckConstraint("length(artifact_path) BETWEEN 1 AND 512 AND substr(artifact_path, 1, 1) <> '/' AND instr(artifact_path, '\\') = 0 AND instr(artifact_path, ':') = 0 AND instr(artifact_path, char(0)) = 0 AND artifact_path NOT LIKE '%//%'", name=op.f('ck_evidence_index_artifact_path_basic')),
        sa.CheckConstraint("length(evidence_id) BETWEEN 23 AND 67 AND substr(evidence_id, 1, 3) = 'ev_' AND substr(evidence_id, 4) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_evidence_index_evidence_id_format')),
        sa.CheckConstraint("length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_evidence_index_sha256_format')),
        sa.CheckConstraint('byte_count BETWEEN 0 AND 1073741824', name=op.f('ck_evidence_index_byte_count_bounds')),
        sa.CheckConstraint('created_at_us >= 0', name=op.f('ck_evidence_index_created_nonnegative')),
        sa.CheckConstraint('length(case_id) BETWEEN 1 AND 128', name=op.f('ck_evidence_index_case_id_length')),
        sa.CheckConstraint('substr(sha256, 1, length(evidence_id) - 3) = substr(evidence_id, 4)', name=op.f('ck_evidence_index_content_address_match')),
        sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_evidence_index_run_id_runs'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_evidence_index')),
        sa.UniqueConstraint('run_id', 'artifact_path', name='uq_evidence_run_artifact_path'),
        sa.UniqueConstraint('run_id', 'case_id', name='uq_evidence_run_case')
        )
        op.create_index('ix_evidence_run_created', 'evidence_index', ['run_id', 'created_at_us'], unique=False)
        op.create_table('finding_occurrences',
        sa.Column('occurrence_id', sa.String(length=36), nullable=False),
        sa.Column('schema_version', sa.String(length=8), nullable=False),
        sa.Column('finding_id', sa.String(length=40), nullable=False),
        sa.Column('project_id', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.String(length=36), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('verdict', sa.String(length=16), nullable=False),
        sa.Column('severity', sa.String(length=16), nullable=False),
        sa.Column('evidence_refs_json', sa.Text(), nullable=False),
        sa.Column('object_context_json', sa.Text(), nullable=False),
        sa.Column('coverage_context_json', sa.Text(), nullable=False),
        sa.Column('created_at_us', sa.BigInteger(), nullable=False),
        sa.CheckConstraint("length(occurrence_id) = 36 AND substr(occurrence_id, 1, 4) = 'occ_' AND substr(occurrence_id, 5) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_finding_occurrences_occurrence_id_format')),
        sa.CheckConstraint("schema_version = '1'", name=op.f('ck_finding_occurrences_occurrence_schema_version_value')),
        sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical', 'unknown')", name=op.f('ck_finding_occurrences_occurrence_severity_value')),
        sa.CheckConstraint("status IN ('APPEARED', 'PRESENT', 'DISAPPEARED', 'REAPPEARED', 'CHANGED')", name=op.f('ck_finding_occurrences_occurrence_status_value')),
        sa.CheckConstraint("verdict IN ('SAFE', 'VULNERABLE', 'INCONCLUSIVE')", name=op.f('ck_finding_occurrences_occurrence_verdict_value')),
        sa.CheckConstraint('created_at_us >= 0', name=op.f('ck_finding_occurrences_occurrence_created_nonnegative')),
        sa.CheckConstraint('length(coverage_context_json) BETWEEN 2 AND 16384', name=op.f('ck_finding_occurrences_occurrence_coverage_context_length')),
        sa.CheckConstraint('length(evidence_refs_json) BETWEEN 1 AND 16384', name=op.f('ck_finding_occurrences_occurrence_evidence_refs_length')),
        sa.CheckConstraint('length(object_context_json) BETWEEN 2 AND 16384', name=op.f('ck_finding_occurrences_occurrence_object_context_length')),
        sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], name=op.f('fk_finding_occurrences_finding_id_findings'), ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_finding_occurrences_project_id_projects'), ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_finding_occurrences_run_id_runs'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('occurrence_id', name=op.f('pk_finding_occurrences')),
        sa.UniqueConstraint('finding_id', 'run_id', name='uq_finding_occurrence_finding_run')
        )
        op.create_index('ix_finding_occurrences_finding_created', 'finding_occurrences', ['finding_id', 'created_at_us'], unique=False)
        op.create_index('ix_finding_occurrences_run_created', 'finding_occurrences', ['run_id', 'created_at_us'], unique=False)
        op.create_table('flow_draft_revisions',
        sa.Column('recording_id', sa.String(length=36), nullable=False),
        sa.Column('revision', sa.Integer(), nullable=False),
        sa.Column('flow_id', sa.String(length=64), nullable=False),
        sa.Column('draft_json', sa.Text(), nullable=False),
        sa.Column('draft_sha256', sa.String(length=64), nullable=False),
        sa.Column('created_at_us', sa.BigInteger(), nullable=False),
        sa.CheckConstraint("length(draft_sha256) = 64 AND draft_sha256 NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_flow_draft_revisions_draft_sha256_format')),
        sa.CheckConstraint("length(flow_id) BETWEEN 1 AND 64 AND substr(flow_id, 1, 1) GLOB '[a-z]' AND flow_id NOT GLOB '*[^a-z0-9_-]*'", name=op.f('ck_flow_draft_revisions_flow_id_format')),
        sa.CheckConstraint('created_at_us >= 0', name=op.f('ck_flow_draft_revisions_created_nonnegative')),
        sa.CheckConstraint('length(draft_json) BETWEEN 2 AND 4194304', name=op.f('ck_flow_draft_revisions_draft_json_size')),
        sa.CheckConstraint('revision >= 1', name=op.f('ck_flow_draft_revisions_revision_positive')),
        sa.ForeignKeyConstraint(['recording_id'], ['recordings.recording_id'], name=op.f('fk_flow_draft_revisions_recording_id_recordings'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('recording_id', 'revision', name=op.f('pk_flow_draft_revisions'))
        )
        op.create_index('ix_flow_drafts_flow_created', 'flow_draft_revisions', ['flow_id', 'created_at_us'], unique=False)
        op.create_table('jobs',
        sa.Column('job_id', sa.String(length=36), nullable=False),
        sa.Column('project_id', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.String(length=36), nullable=True),
        sa.Column('recording_id', sa.String(length=36), nullable=True),
        sa.Column('operation_type', sa.String(length=64), nullable=False),
        sa.Column('state', sa.String(length=16), nullable=False),
        sa.Column('idempotency_key', sa.String(length=128), nullable=False),
        sa.Column('request_hash', sa.String(length=64), nullable=False),
        sa.Column('attempt', sa.Integer(), nullable=False),
        sa.Column('max_attempts', sa.Integer(), nullable=False),
        sa.Column('available_at_us', sa.BigInteger(), nullable=False),
        sa.Column('lease_owner', sa.String(length=128), nullable=True),
        sa.Column('fencing_token', sa.BigInteger(), nullable=False),
        sa.Column('lease_expires_at_us', sa.BigInteger(), nullable=True),
        sa.Column('cancel_requested_at_us', sa.BigInteger(), nullable=True),
        sa.Column('created_at_us', sa.BigInteger(), nullable=False),
        sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
        sa.CheckConstraint("lease_owner IS NULL OR (length(lease_owner) BETWEEN 1 AND 128 AND lease_owner NOT GLOB '*[^A-Za-z0-9._:-]*')", name=op.f('ck_jobs_lease_owner_format')),
        sa.CheckConstraint("length(job_id) = 36 AND substr(job_id, 1, 4) = 'job_' AND substr(job_id, 5) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_jobs_job_id_format')),
        sa.CheckConstraint("length(operation_type) BETWEEN 1 AND 64 AND operation_type NOT GLOB '*[^A-Z0-9_]*'", name=op.f('ck_jobs_operation_type_format')),
        sa.CheckConstraint("length(request_hash) = 64 AND request_hash NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_jobs_request_hash_format')),
        sa.CheckConstraint("state <> 'RUNNING' OR (lease_owner IS NOT NULL AND fencing_token > 0 AND lease_expires_at_us IS NOT NULL)", name=op.f('ck_jobs_running_lease_required')),
        sa.CheckConstraint("state IN ('PENDING', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED', 'CANCELLED')", name=op.f('ck_jobs_state_value')),
        sa.CheckConstraint('(attempt = 0 AND fencing_token = 0 AND lease_owner IS NULL AND lease_expires_at_us IS NULL) OR (attempt > 0 AND fencing_token > 0)', name=op.f('ck_jobs_attempt_fencing_relation')),
        sa.CheckConstraint('(lease_owner IS NULL AND lease_expires_at_us IS NULL) OR (lease_owner IS NOT NULL AND lease_expires_at_us IS NOT NULL)', name=op.f('ck_jobs_lease_pair')),
        sa.CheckConstraint('(run_id IS NOT NULL AND recording_id IS NULL) OR (run_id IS NULL AND recording_id IS NOT NULL)', name=op.f('ck_jobs_exactly_one_target')),
        sa.CheckConstraint('attempt >= 0 AND max_attempts >= 1 AND attempt <= max_attempts', name=op.f('ck_jobs_attempt_bounds')),
        sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us AND available_at_us >= 0 AND (lease_expires_at_us IS NULL OR lease_expires_at_us >= 0) AND (cancel_requested_at_us IS NULL OR cancel_requested_at_us >= created_at_us)', name=op.f('ck_jobs_time_bounds')),
        sa.CheckConstraint('fencing_token >= 0', name=op.f('ck_jobs_fencing_nonnegative')),
        sa.CheckConstraint('length(idempotency_key) BETWEEN 1 AND 128', name=op.f('ck_jobs_idempotency_key_length')),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_jobs_project_id_projects'), ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['recording_id'], ['recordings.recording_id'], name=op.f('fk_jobs_recording_id_recordings'), ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_jobs_run_id_runs'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('job_id', name=op.f('pk_jobs')),
        sa.UniqueConstraint('project_id', 'operation_type', 'idempotency_key', name='uq_jobs_idempotency_scope'),
        sa.UniqueConstraint('recording_id', name='uq_jobs_recording_id'),
        sa.UniqueConstraint('run_id', name='uq_jobs_run_id')
        )
        op.create_index('ix_jobs_state_available', 'jobs', ['state', 'available_at_us'], unique=False)
        op.create_index('ix_jobs_state_lease_expires', 'jobs', ['state', 'lease_expires_at_us'], unique=False)
        op.create_table('regression_baselines',
        sa.Column('baseline_id', sa.String(length=41), nullable=False),
        sa.Column('schema_version', sa.String(length=8), nullable=False),
        sa.Column('project_id', sa.String(length=64), nullable=False),
        sa.Column('accepted_run_id', sa.String(length=36), nullable=False),
        sa.Column('finding_refs_json', sa.Text(), nullable=False),
        sa.Column('coverage_ids_json', sa.Text(), nullable=False),
        sa.Column('coverage_digest', sa.String(length=64), nullable=False),
        sa.Column('request_snapshot_sha256', sa.String(length=64), nullable=False),
        sa.Column('engine_version', sa.String(length=64), nullable=False),
        sa.Column('protocol_versions_json', sa.Text(), nullable=False),
        sa.Column('actor', sa.String(length=128), nullable=False),
        sa.Column('reason', sa.String(length=1024), nullable=False),
        sa.Column('accepted_at_us', sa.BigInteger(), nullable=False),
        sa.CheckConstraint("length(baseline_id) = 41 AND substr(baseline_id, 1, 9) = 'baseline_' AND substr(baseline_id, 10) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_regression_baselines_baseline_id_format')),
        sa.CheckConstraint("length(coverage_digest) = 64 AND coverage_digest NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_regression_baselines_baseline_coverage_digest_format')),
        sa.CheckConstraint("length(request_snapshot_sha256) = 64 AND request_snapshot_sha256 NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_regression_baselines_baseline_snapshot_hash_format')),
        sa.CheckConstraint("schema_version = '1'", name=op.f('ck_regression_baselines_baseline_schema_version_value')),
        sa.CheckConstraint('accepted_at_us >= 0', name=op.f('ck_regression_baselines_baseline_accepted_nonnegative')),
        sa.CheckConstraint('length(actor) BETWEEN 1 AND 128', name=op.f('ck_regression_baselines_baseline_actor_length')),
        sa.CheckConstraint('length(coverage_ids_json) BETWEEN 2 AND 524288', name=op.f('ck_regression_baselines_baseline_coverage_ids_length')),
        sa.CheckConstraint('length(finding_refs_json) BETWEEN 2 AND 524288', name=op.f('ck_regression_baselines_baseline_finding_refs_length')),
        sa.CheckConstraint('length(protocol_versions_json) BETWEEN 3 AND 4096', name=op.f('ck_regression_baselines_baseline_protocol_versions_length')),
        sa.CheckConstraint('length(reason) BETWEEN 1 AND 1024', name=op.f('ck_regression_baselines_baseline_reason_length')),
        sa.ForeignKeyConstraint(['accepted_run_id'], ['runs.run_id'], name=op.f('fk_regression_baselines_accepted_run_id_runs'), ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_regression_baselines_project_id_projects'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('baseline_id', name=op.f('pk_regression_baselines'))
        )
        op.create_index('ix_regression_baselines_project_accepted', 'regression_baselines', ['project_id', 'accepted_at_us'], unique=False)
        op.create_table('gate_results',
        sa.Column('gate_result_id', sa.String(length=37), nullable=False),
        sa.Column('schema_version', sa.String(length=8), nullable=False),
        sa.Column('baseline_id', sa.String(length=41), nullable=False),
        sa.Column('project_id', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.String(length=36), nullable=False),
        sa.Column('policy_version', sa.String(length=16), nullable=False),
        sa.Column('input_hash', sa.String(length=64), nullable=False),
        sa.Column('reasons_json', sa.Text(), nullable=False),
        sa.Column('decision', sa.String(length=8), nullable=False),
        sa.Column('evaluated_at_us', sa.BigInteger(), nullable=False),
        sa.CheckConstraint("decision IN ('PASS', 'BLOCK', 'ERROR')", name=op.f('ck_gate_results_gate_result_decision_value')),
        sa.CheckConstraint("length(gate_result_id) = 37 AND substr(gate_result_id, 1, 5) = 'gate_' AND substr(gate_result_id, 6) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_gate_results_gate_result_id_format')),
        sa.CheckConstraint("length(input_hash) = 64 AND input_hash NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_gate_results_gate_result_input_hash_format')),
        sa.CheckConstraint("policy_version = 'gate-v1'", name=op.f('ck_gate_results_gate_result_policy_version_value')),
        sa.CheckConstraint("schema_version = '1'", name=op.f('ck_gate_results_gate_result_schema_version_value')),
        sa.CheckConstraint('evaluated_at_us >= 0', name=op.f('ck_gate_results_gate_result_evaluated_nonnegative')),
        sa.CheckConstraint('length(reasons_json) BETWEEN 2 AND 524288', name=op.f('ck_gate_results_gate_result_reasons_length')),
        sa.ForeignKeyConstraint(['baseline_id'], ['regression_baselines.baseline_id'], name=op.f('fk_gate_results_baseline_id_regression_baselines'), ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_gate_results_project_id_projects'), ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_gate_results_run_id_runs'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('gate_result_id', name=op.f('pk_gate_results')),
        sa.UniqueConstraint('baseline_id', 'run_id', 'policy_version', 'input_hash', name='uq_gate_result_input')
        )
        op.create_index('ix_gate_results_baseline_run', 'gate_results', ['baseline_id', 'run_id', 'evaluated_at_us'], unique=False)
        op.create_table('job_events',
        sa.Column('job_id', sa.String(length=36), nullable=False),
        sa.Column('sequence', sa.Integer(), nullable=False),
        sa.Column('event_type', sa.String(length=64), nullable=False),
        sa.Column('source_state', sa.String(length=16), nullable=True),
        sa.Column('target_state', sa.String(length=16), nullable=True),
        sa.Column('occurred_at_us', sa.BigInteger(), nullable=False),
        sa.Column('metadata_json', sa.Text(), nullable=False),
        sa.CheckConstraint("length(event_type) BETWEEN 1 AND 64 AND event_type NOT GLOB '*[^A-Z0-9_]*'", name=op.f('ck_job_events_event_type_format')),
        sa.CheckConstraint("source_state IS NULL OR source_state IN ('PENDING', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED', 'CANCELLED')", name=op.f('ck_job_events_source_state_value')),
        sa.CheckConstraint("target_state IS NULL OR target_state IN ('PENDING', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED', 'CANCELLED')", name=op.f('ck_job_events_target_state_value')),
        sa.CheckConstraint('length(metadata_json) BETWEEN 2 AND 4096', name=op.f('ck_job_events_metadata_length')),
        sa.CheckConstraint('occurred_at_us >= 0', name=op.f('ck_job_events_occurred_nonnegative')),
        sa.CheckConstraint('sequence >= 1', name=op.f('ck_job_events_sequence_positive')),
        sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], name=op.f('fk_job_events_job_id_jobs'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('job_id', 'sequence', name=op.f('pk_job_events'))
        )
        op.create_index('ix_job_events_job_occurred', 'job_events', ['job_id', 'occurred_at_us'], unique=False)
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_index('ix_job_events_job_occurred', table_name='job_events')
        op.drop_table('job_events')
        op.drop_index('ix_gate_results_baseline_run', table_name='gate_results')
        op.drop_table('gate_results')
        op.drop_index('ix_regression_baselines_project_accepted', table_name='regression_baselines')
        op.drop_table('regression_baselines')
        op.drop_index('ix_jobs_state_lease_expires', table_name='jobs')
        op.drop_index('ix_jobs_state_available', table_name='jobs')
        op.drop_table('jobs')
        op.drop_index('ix_flow_drafts_flow_created', table_name='flow_draft_revisions')
        op.drop_table('flow_draft_revisions')
        op.drop_index('ix_finding_occurrences_run_created', table_name='finding_occurrences')
        op.drop_index('ix_finding_occurrences_finding_created', table_name='finding_occurrences')
        op.drop_table('finding_occurrences')
        op.drop_index('ix_evidence_run_created', table_name='evidence_index')
        op.drop_table('evidence_index')
        op.drop_index('ix_runs_project_created', table_name='runs')
        op.drop_index('ix_runs_lifecycle_updated', table_name='runs')
        op.drop_table('runs')
        op.drop_index('ix_requirements_project_created', table_name='requirements')
        op.drop_table('requirements')
        op.drop_index('ix_recordings_state_updated', table_name='recordings')
        op.drop_index('ix_recordings_project_created', table_name='recordings')
        op.drop_table('recordings')
        op.drop_index('ix_findings_project_updated', table_name='findings')
        op.drop_table('findings')
        op.drop_index('ix_permission_profiles_project_updated', table_name='execution_profiles')
        op.drop_table('execution_profiles')
        op.drop_index('uq_contract_versions_active', table_name='contract_versions', sqlite_where=sa.text("status = 'ACTIVE'"))
        op.drop_index('ix_contract_versions_project_status', table_name='contract_versions')
        op.drop_table('contract_versions')
        op.drop_index('ix_contract_candidates_project_created', table_name='contract_candidates')
        op.drop_table('contract_candidates')
        op.execute("DROP TRIGGER IF EXISTS projects_governed_binding_update")
        op.execute("DROP TRIGGER IF EXISTS projects_governed_binding_insert")
        op.drop_index('ix_projects_status_updated', table_name='projects')
        op.drop_table('projects')
        op.drop_table('llm_profiles')
        # ### end Alembic commands ###
