# 为 fresh 1.1.0 数据目录显式建立完整 Business Boundary v2 数据库基线。

"""business boundary v2 baseline

Revision ID: 0001_business_boundary_v2
Revises:
Create Date: 2026-09-02 20:29:47.401126
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_business_boundary_v2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_profiles',
    sa.Column('profile_name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('reasoning_effort', sa.String(length=16), nullable=True),
    sa.Column('base_url', sa.String(length=2048), nullable=True),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('max_input_bytes', sa.Integer(), nullable=False),
    sa.Column('max_output_bytes', sa.Integer(), nullable=False),
    sa.Column('max_budget_microusd', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('secret_ref', sa.String(length=256), nullable=True),
    sa.Column('allow_local_http', sa.Boolean(), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("length(profile_name) BETWEEN 1 AND 128 AND substr(profile_name, 1, 1) GLOB '[a-z]' AND profile_name NOT GLOB '*[^a-z0-9_-]*'", name=op.f('ck_llm_profiles_profile_name_format')),
    sa.CheckConstraint("provider IN ('openai', 'deepseek', 'gemini', 'openai_compatible')", name=op.f('ck_llm_profiles_provider_value')),
    sa.CheckConstraint('base_url IS NULL OR length(base_url) BETWEEN 1 AND 2048', name=op.f('ck_llm_profiles_base_url_length')),
    sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_llm_profiles_time_order')),
    sa.CheckConstraint('length(model) BETWEEN 1 AND 256', name=op.f('ck_llm_profiles_model_length')),
    sa.CheckConstraint('max_budget_microusd BETWEEN 0 AND 1000000000', name=op.f('ck_llm_profiles_budget_range')),
    sa.CheckConstraint('max_input_bytes BETWEEN 1 AND 1048576', name=op.f('ck_llm_profiles_input_bytes_range')),
    sa.CheckConstraint('max_output_bytes BETWEEN 1 AND 1048576', name=op.f('ck_llm_profiles_output_bytes_range')),
    sa.CheckConstraint('secret_ref IS NULL OR length(secret_ref) BETWEEN 1 AND 256', name=op.f('ck_llm_profiles_secret_ref_length')),
    sa.CheckConstraint('timeout_ms BETWEEN 100 AND 300000', name=op.f('ck_llm_profiles_timeout_range')),
    sa.PrimaryKeyConstraint('profile_name', name=op.f('pk_llm_profiles'))
    )
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('governed_contract_id', sa.String(length=128), nullable=True),
    sa.Column('governed_contract_version', sa.Integer(), nullable=True),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("length(project_id) BETWEEN 1 AND 64 AND substr(project_id, 1, 1) GLOB '[a-z]' AND project_id NOT GLOB '*[^a-z0-9_-]*'", name=op.f('ck_projects_project_id_format')),
    sa.CheckConstraint("status IN ('DRAFT', 'READY', 'ARCHIVED')", name=op.f('ck_projects_status_value')),
    sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_projects_time_order')),
    sa.CheckConstraint('length(name) BETWEEN 1 AND 128', name=op.f('ck_projects_name_length')),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_projects'))
    )
    op.create_index('ix_projects_status_updated', 'projects', ['status', 'updated_at_us'], unique=False)
    op.create_table('ai_assistance_settings',
    sa.Column('settings_key', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('default_profile_name', sa.String(length=128), nullable=True),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("settings_key = 'default'", name=op.f('ck_ai_assistance_settings_settings_key_value')),
    sa.ForeignKeyConstraint(['default_profile_name'], ['llm_profiles.profile_name'], name=op.f('fk_ai_assistance_settings_default_profile_name_llm_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('settings_key', name=op.f('pk_ai_assistance_settings'))
    )
    op.create_table('application_understanding',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('source_root', sa.String(length=32768), nullable=False),
    sa.Column('confirmed_endpoint', sa.String(length=2048), nullable=True),
    sa.Column('endpoint_source_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('endpoint_confirmed_at_us', sa.BigInteger(), nullable=True),
    sa.Column('endpoint_last_checked_at_us', sa.BigInteger(), nullable=True),
    sa.Column('endpoint_reachable', sa.Boolean(), nullable=True),
    sa.Column('source_analysis_authorized', sa.Boolean(), nullable=False),
    sa.Column('source_analysis_authorized_at_us', sa.BigInteger(), nullable=True),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('analysis_completed_at_us', sa.BigInteger(), nullable=True),
    sa.Column('role_candidates_json', sa.Text(), nullable=False),
    sa.Column('action_candidates_json', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('(confirmed_endpoint IS NULL AND endpoint_source_fingerprint IS NULL AND endpoint_confirmed_at_us IS NULL AND endpoint_last_checked_at_us IS NULL AND endpoint_reachable IS NULL) OR (confirmed_endpoint IS NOT NULL AND endpoint_source_fingerprint IS NOT NULL AND endpoint_confirmed_at_us IS NOT NULL AND endpoint_last_checked_at_us IS NOT NULL AND endpoint_reachable IS NOT NULL)', name=op.f('ck_application_understanding_endpoint_state_complete')),
    sa.CheckConstraint('(source_analysis_authorized = 0 AND source_analysis_authorized_at_us IS NULL) OR (source_analysis_authorized = 1 AND source_analysis_authorized_at_us IS NOT NULL)', name=op.f('ck_application_understanding_analysis_authorization_state')),
    sa.CheckConstraint('(source_fingerprint IS NULL AND analysis_completed_at_us IS NULL) OR (source_fingerprint IS NOT NULL AND length(source_fingerprint) = 64 AND analysis_completed_at_us IS NOT NULL AND source_analysis_authorized = 1)', name=op.f('ck_application_understanding_analysis_result_state')),
    sa.CheckConstraint('confirmed_endpoint IS NULL OR length(confirmed_endpoint) BETWEEN 1 AND 2048', name=op.f('ck_application_understanding_endpoint_length')),
    sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_application_understanding_time_order')),
    sa.CheckConstraint('endpoint_source_fingerprint IS NULL OR length(endpoint_source_fingerprint) = 64', name=op.f('ck_application_understanding_endpoint_fingerprint_length')),
    sa.CheckConstraint('length(action_candidates_json) BETWEEN 2 AND 2097152', name=op.f('ck_application_understanding_actions_json_length')),
    sa.CheckConstraint('length(role_candidates_json) BETWEEN 2 AND 1048576', name=op.f('ck_application_understanding_roles_json_length')),
    sa.CheckConstraint('length(source_root) BETWEEN 1 AND 32768', name=op.f('ck_application_understanding_source_root_length')),
    sa.CheckConstraint('revision BETWEEN 0 AND 1000000', name=op.f('ck_application_understanding_revision_range')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_application_understanding_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_application_understanding')),
    sa.UniqueConstraint('source_root', name='uq_application_understanding_source_root')
    )
    op.create_index('ix_application_understanding_updated', 'application_understanding', ['updated_at_us'], unique=False)
    op.create_table('boundary_proposals',
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('source_snapshot_json', sa.Text(), nullable=False),
    sa.Column('proposed_actors_json', sa.Text(), nullable=False),
    sa.Column('proposed_actions_json', sa.Text(), nullable=False),
    sa.Column('proposed_permissions_json', sa.Text(), nullable=False),
    sa.Column('unresolved_questions_json', sa.Text(), nullable=False),
    sa.Column('provenance', sa.String(length=512), nullable=False),
    sa.Column('proposal_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_boundary_proposals_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proposal_id', name=op.f('pk_boundary_proposals'))
    )
    op.create_index('ix_boundary_proposals_project', 'boundary_proposals', ['project_id', 'created_at_us'], unique=False)
    op.create_table('business_action_revisions',
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('primary_resource_concept', sa.String(length=128), nullable=False),
    sa.Column('operation_kind', sa.String(length=16), nullable=False),
    sa.Column('state_changing', sa.Boolean(), nullable=False),
    sa.Column('effect_catalog_json', sa.Text(), nullable=False),
    sa.Column('semantic_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('effective_state', sa.String(length=16), nullable=False),
    sa.Column('approval_json', sa.Text(), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("effective_state IN ('ACTIVE', 'SUPERSEDED', 'RETIRED')", name=op.f('ck_business_action_revisions_effective_state_value')),
    sa.CheckConstraint("operation_kind IN ('READ', 'CHANGE', 'DELETE', 'EXPORT', 'ADMIN', 'CUSTOM')", name=op.f('ck_business_action_revisions_operation_kind_value')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_business_action_revisions_revision_positive')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_business_action_revisions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id', 'revision', name=op.f('pk_business_action_revisions'))
    )
    op.create_index('ix_business_action_revisions_project', 'business_action_revisions', ['project_id', 'created_at_us'], unique=False)
    op.create_table('business_actor_revisions',
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('semantic_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('effective_state', sa.String(length=16), nullable=False),
    sa.Column('approval_json', sa.Text(), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("effective_state IN ('ACTIVE', 'SUPERSEDED', 'RETIRED')", name=op.f('ck_business_actor_revisions_effective_state_value')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_business_actor_revisions_revision_positive')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_business_actor_revisions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id', 'revision', name=op.f('pk_business_actor_revisions'))
    )
    op.create_index('ix_business_actor_revisions_project', 'business_actor_revisions', ['project_id', 'created_at_us'], unique=False)
    op.create_table('change_manifests',
    sa.Column('change_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('claimed_paths_json', sa.Text(), nullable=False),
    sa.Column('repair_reference_json', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.String(length=128), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('created_at_us >= 0', name=op.f('ck_change_manifests_created_nonnegative')),
    sa.CheckConstraint('length(change_id) = 36', name=op.f('ck_change_manifests_change_id_length')),
    sa.CheckConstraint('length(claimed_paths_json) BETWEEN 2 AND 131072', name=op.f('ck_change_manifests_claimed_paths_json_length')),
    sa.CheckConstraint('length(reason) BETWEEN 1 AND 512', name=op.f('ck_change_manifests_reason_length')),
    sa.CheckConstraint('length(submitted_by) BETWEEN 1 AND 128', name=op.f('ck_change_manifests_submitted_by_length')),
    sa.CheckConstraint('repair_reference_json IS NULL OR length(repair_reference_json) BETWEEN 2 AND 1024', name=op.f('ck_change_manifests_repair_reference_json_length')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_change_manifests_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('change_id', name=op.f('pk_change_manifests'))
    )
    op.create_index('ix_change_manifests_project_created', 'change_manifests', ['project_id', 'created_at_us'], unique=False)
    op.create_table('contract_versions',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('contract_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('provenance_json', sa.Text(), nullable=False),
    sa.Column('supersedes_version', sa.Integer(), nullable=True),
    sa.Column('audit_json', sa.Text(), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'REVIEW', 'ACTIVE', 'SUPERSEDED', 'REJECTED')", name=op.f('ck_contract_versions_status_value')),
    sa.CheckConstraint('(version = 1 AND supersedes_version IS NULL) OR (version > 1 AND supersedes_version = version - 1)', name=op.f('ck_contract_versions_supersedes_version_order')),
    sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_contract_versions_time_order')),
    sa.CheckConstraint('length(audit_json) BETWEEN 2 AND 131072', name=op.f('ck_contract_versions_audit_json_length')),
    sa.CheckConstraint('length(contract_id) BETWEEN 1 AND 128', name=op.f('ck_contract_versions_contract_id_length')),
    sa.CheckConstraint('length(provenance_json) BETWEEN 2 AND 1048576', name=op.f('ck_contract_versions_provenance_json_length')),
    sa.CheckConstraint('length(snapshot_json) BETWEEN 2 AND 1048576', name=op.f('ck_contract_versions_snapshot_json_length')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_contract_versions_version_positive')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_contract_versions_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'contract_id', 'version', name=op.f('pk_contract_versions'))
    )
    op.create_index('ix_contract_versions_project_status', 'contract_versions', ['project_id', 'status', 'updated_at_us'], unique=False)
    op.create_index('uq_contract_versions_active', 'contract_versions', ['project_id', 'contract_id'], unique=True, sqlite_where=sa.text("status = 'ACTIVE'"))
    op.create_table('execution_profiles',
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('source_path', sa.String(length=2048), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('contract_id', sa.String(length=128), nullable=False),
    sa.Column('contract_version', sa.Integer(), nullable=False),
    sa.Column('contract_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('plan_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=128), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("length(profile_id) BETWEEN 1 AND 64 AND substr(profile_id, 1, 1) GLOB '[a-z]' AND profile_id NOT GLOB '*[^a-z0-9_-]*'", name=op.f('ck_execution_profiles_profile_id_format')),
    sa.CheckConstraint('contract_version >= 1', name=op.f('ck_execution_profiles_profile_contract_version')),
    sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_execution_profiles_profile_time_order')),
    sa.CheckConstraint('length(source_hash) = 64 AND length(contract_fingerprint) = 64 AND length(plan_fingerprint) = 64', name=op.f('ck_execution_profiles_profile_hash_lengths')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_execution_profiles_project_id_projects')),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('pk_execution_profiles'))
    )
    op.create_index('ix_permission_profiles_project_updated', 'execution_profiles', ['project_id', 'updated_at_us'], unique=False)
    op.create_table('findings',
    sa.Column('finding_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('identity_json', sa.Text(), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("length(finding_id) = 40 AND substr(finding_id, 1, 8) = 'finding_' AND substr(finding_id, 9) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_findings_finding_id_format')),
    sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_findings_finding_time_order')),
    sa.CheckConstraint('length(identity_json) BETWEEN 1 AND 16384', name=op.f('ck_findings_finding_identity_length')),
    sa.CheckConstraint('length(project_id) BETWEEN 1 AND 64', name=op.f('ck_findings_finding_project_id_length')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_findings_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('finding_id', name=op.f('pk_findings'))
    )
    op.create_index('ix_findings_project_updated', 'findings', ['project_id', 'updated_at_us'], unique=False)
    op.create_table('project_policy_states',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('policy_epoch', sa.Integer(), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('policy_epoch >= 0', name=op.f('ck_project_policy_states_policy_epoch_nonnegative')),
    sa.CheckConstraint('updated_at_us >= 0', name=op.f('ck_project_policy_states_updated_nonnegative')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_project_policy_states_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project_policy_states'))
    )
    op.create_table('recordings',
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('parent_recording_id', sa.String(length=36), nullable=True),
    sa.Column('flow_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.Column('started_at_us', sa.BigInteger(), nullable=True),
    sa.Column('capture_finished_at_us', sa.BigInteger(), nullable=True),
    sa.Column('finished_at_us', sa.BigInteger(), nullable=True),
    sa.Column('pending_terminal_state', sa.String(length=24), nullable=True),
    sa.Column('reason_codes_json', sa.Text(), nullable=False),
    sa.Column('state_events_json', sa.Text(), nullable=False),
    sa.Column('browser_events_json', sa.Text(), nullable=False),
    sa.CheckConstraint("(state IN ('COMPLETED', 'FAILED', 'CANCELLED', 'SAFETY_STOPPED') AND finished_at_us IS NOT NULL) OR (state NOT IN ('COMPLETED', 'FAILED', 'CANCELLED', 'SAFETY_STOPPED') AND finished_at_us IS NULL)", name=op.f('ck_recordings_terminal_finish_matrix')),
    sa.CheckConstraint("length(flow_id) BETWEEN 1 AND 64 AND substr(flow_id, 1, 1) GLOB '[a-z]' AND flow_id NOT GLOB '*[^a-z0-9_-]*'", name=op.f('ck_recordings_flow_id_format')),
    sa.CheckConstraint("length(recording_id) = 36 AND substr(recording_id, 1, 4) = 'rec_' AND substr(recording_id, 5) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_recordings_recording_id_format')),
    sa.CheckConstraint("pending_terminal_state IS NULL OR pending_terminal_state IN ('FAILED', 'CANCELLED', 'SAFETY_STOPPED')", name=op.f('ck_recordings_pending_terminal_state_value')),
    sa.CheckConstraint("state IN ('CREATED', 'STARTING', 'RECORDING', 'CLEANING', 'PROCESSING', 'PENDING_REVIEW', 'COMPLETED', 'FAILED', 'CANCELLED', 'SAFETY_STOPPED')", name=op.f('ck_recordings_state_value')),
    sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us AND (started_at_us IS NULL OR started_at_us >= created_at_us) AND (capture_finished_at_us IS NULL OR capture_finished_at_us >= started_at_us) AND (finished_at_us IS NULL OR finished_at_us >= updated_at_us)', name=op.f('ck_recordings_time_order')),
    sa.CheckConstraint('length(reason_codes_json) BETWEEN 2 AND 8192 AND length(state_events_json) BETWEEN 2 AND 131072 AND length(browser_events_json) BETWEEN 2 AND 4194304', name=op.f('ck_recordings_json_size_bounds')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_recordings_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('recording_id', name=op.f('pk_recordings'))
    )
    op.create_index('ix_recordings_parent_purpose', 'recordings', ['parent_recording_id', 'purpose'], unique=False)
    op.create_index('ix_recordings_project_created', 'recordings', ['project_id', 'created_at_us'], unique=False)
    op.create_index('ix_recordings_state_updated', 'recordings', ['state', 'updated_at_us'], unique=False)
    op.create_table('runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('contract_id', sa.String(length=128), nullable=False),
    sa.Column('contract_version', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('lifecycle', sa.String(length=24), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=True),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.Column('finished_at_us', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("(lifecycle = 'COMPLETED' AND verdict IS NOT NULL) OR (lifecycle <> 'COMPLETED' AND verdict IS NULL)", name=op.f('ck_runs_lifecycle_verdict_matrix')),
    sa.CheckConstraint("length(run_id) = 36 AND substr(run_id, 1, 4) = 'run_' AND substr(run_id, 5) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_runs_run_id_format')),
    sa.CheckConstraint("lifecycle IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'SAFETY_STOPPED')", name=op.f('ck_runs_lifecycle_value')),
    sa.CheckConstraint("verdict IS NULL OR verdict IN ('PASS', 'BLOCK', 'INCONCLUSIVE')", name=op.f('ck_runs_verdict_value')),
    sa.CheckConstraint('contract_version >= 1', name=op.f('ck_runs_contract_version_positive')),
    sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us AND (finished_at_us IS NULL OR finished_at_us >= created_at_us)', name=op.f('ck_runs_time_order')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_runs_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_runs'))
    )
    op.create_index('ix_runs_lifecycle_updated', 'runs', ['lifecycle', 'updated_at_us'], unique=False)
    op.create_index('ix_runs_project_created', 'runs', ['project_id', 'created_at_us'], unique=False)
    op.create_table('source_revision_snapshots',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('understanding_revision', sa.Integer(), nullable=False),
    sa.Column('files_json', sa.Text(), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('created_at_us >= 0', name=op.f('ck_source_revision_snapshots_created_nonnegative')),
    sa.CheckConstraint('length(files_json) BETWEEN 2 AND 1048576', name=op.f('ck_source_revision_snapshots_files_json_length')),
    sa.CheckConstraint('length(snapshot_id) = 36', name=op.f('ck_source_revision_snapshots_snapshot_id_length')),
    sa.CheckConstraint('length(source_fingerprint) = 64', name=op.f('ck_source_revision_snapshots_fingerprint_length')),
    sa.CheckConstraint('understanding_revision BETWEEN 0 AND 1000000', name=op.f('ck_source_revision_snapshots_understanding_revision_range')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_source_revision_snapshots_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_source_revision_snapshots')),
    sa.UniqueConstraint('project_id', 'source_fingerprint', name='uq_source_revision_project_fingerprint')
    )
    op.create_index('ix_source_revision_project_created', 'source_revision_snapshots', ['project_id', 'created_at_us'], unique=False)
    op.create_table('action_implementation_bindings',
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('action_revision', sa.Integer(), nullable=False),
    sa.Column('understanding_revision', sa.Integer(), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('action_candidate_ids_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason_codes_json', sa.Text(), nullable=False),
    sa.Column('binding_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("status IN ('CURRENT', 'STALE', 'MISSING', 'AMBIGUOUS')", name=op.f('ck_action_implementation_bindings_status_value')),
    sa.ForeignKeyConstraint(['action_id', 'action_revision'], ['business_action_revisions.action_id', 'business_action_revisions.revision'], name=op.f('fk_action_implementation_bindings_action_id_business_action_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id', 'action_revision', name=op.f('pk_action_implementation_bindings'))
    )
    op.create_table('actor_implementation_bindings',
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('actor_revision', sa.Integer(), nullable=False),
    sa.Column('understanding_revision', sa.Integer(), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('role_candidate_ids_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason_codes_json', sa.Text(), nullable=False),
    sa.Column('binding_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("status IN ('CURRENT', 'STALE', 'MISSING', 'AMBIGUOUS')", name=op.f('ck_actor_implementation_bindings_status_value')),
    sa.ForeignKeyConstraint(['actor_id', 'actor_revision'], ['business_actor_revisions.actor_id', 'business_actor_revisions.revision'], name=op.f('fk_actor_implementation_bindings_actor_id_business_actor_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id', 'actor_revision', name=op.f('pk_actor_implementation_bindings'))
    )
    op.create_table('boundary_proposal_decisions',
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('proposal_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=False),
    sa.Column('decided_at_us', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.CheckConstraint("decision IN ('APPROVED', 'REJECTED')", name=op.f('ck_boundary_proposal_decisions_decision_value')),
    sa.ForeignKeyConstraint(['proposal_id'], ['boundary_proposals.proposal_id'], name=op.f('fk_boundary_proposal_decisions_proposal_id_boundary_proposals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('decision_id', name=op.f('pk_boundary_proposal_decisions')),
    sa.UniqueConstraint('proposal_id', name='uq_boundary_decision_proposal')
    )
    op.create_table('business_actions',
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_business_actions_time_order')),
    sa.CheckConstraint('current_revision >= 1', name=op.f('ck_business_actions_current_revision_positive')),
    sa.ForeignKeyConstraint(['action_id', 'current_revision'], ['business_action_revisions.action_id', 'business_action_revisions.revision'], name=op.f('fk_business_actions_action_id_business_action_revisions'), ondelete='RESTRICT', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_business_actions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id', name=op.f('pk_business_actions'))
    )
    op.create_index('ix_business_actions_project', 'business_actions', ['project_id', 'updated_at_us'], unique=False)
    op.create_table('business_actors',
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_business_actors_time_order')),
    sa.CheckConstraint('current_revision >= 1', name=op.f('ck_business_actors_current_revision_positive')),
    sa.ForeignKeyConstraint(['actor_id', 'current_revision'], ['business_actor_revisions.actor_id', 'business_actor_revisions.revision'], name=op.f('fk_business_actors_actor_id_business_actor_revisions'), ondelete='RESTRICT', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_business_actors_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id', name=op.f('pk_business_actors'))
    )
    op.create_index('ix_business_actors_project', 'business_actors', ['project_id', 'updated_at_us'], unique=False)
    op.create_table('change_impact_assessments',
    sa.Column('change_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('change_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('reason_codes_json', sa.Text(), nullable=False),
    sa.Column('impacts_json', sa.Text(), nullable=False),
    sa.Column('impact_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('created_at_us >= 0', name=op.f('ck_change_impact_assessments_created_nonnegative')),
    sa.CheckConstraint('length(change_fingerprint) = 64', name=op.f('ck_change_impact_assessments_change_fingerprint_length')),
    sa.CheckConstraint('length(impact_fingerprint) = 64', name=op.f('ck_change_impact_assessments_impact_fingerprint_length')),
    sa.CheckConstraint('length(impacts_json) BETWEEN 2 AND 2097152', name=op.f('ck_change_impact_assessments_impacts_json_length')),
    sa.CheckConstraint('length(reason_codes_json) BETWEEN 2 AND 8192', name=op.f('ck_change_impact_assessments_reasons_json_length')),
    sa.ForeignKeyConstraint(['change_id'], ['change_manifests.change_id'], name=op.f('fk_change_impact_assessments_change_id_change_manifests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_change_impact_assessments_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('change_id', name=op.f('pk_change_impact_assessments'))
    )
    op.create_index('ix_change_impacts_project_created', 'change_impact_assessments', ['project_id', 'created_at_us'], unique=False)
    op.create_table('evidence_index',
    sa.Column('evidence_id', sa.String(length=67), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('artifact_path', sa.String(length=512, collation='NOCASE'), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_count', sa.BigInteger(), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("length(artifact_path) BETWEEN 1 AND 512 AND substr(artifact_path, 1, 1) <> '/' AND instr(artifact_path, '\\') = 0 AND instr(artifact_path, ':') = 0 AND instr(artifact_path, char(0)) = 0 AND artifact_path NOT LIKE '%//%'", name=op.f('ck_evidence_index_artifact_path_basic')),
    sa.CheckConstraint("length(evidence_id) BETWEEN 23 AND 67 AND substr(evidence_id, 1, 3) = 'ev_' AND substr(evidence_id, 4) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_evidence_index_evidence_id_format')),
    sa.CheckConstraint("length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_evidence_index_sha256_format')),
    sa.CheckConstraint('byte_count BETWEEN 0 AND 1073741824', name=op.f('ck_evidence_index_byte_count_bounds')),
    sa.CheckConstraint('created_at_us >= 0', name=op.f('ck_evidence_index_created_nonnegative')),
    sa.CheckConstraint('length(case_id) BETWEEN 1 AND 128', name=op.f('ck_evidence_index_case_id_length')),
    sa.CheckConstraint('substr(sha256, 1, length(evidence_id) - 3) = substr(evidence_id, 4)', name=op.f('ck_evidence_index_content_address_match')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_evidence_index_run_id_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_evidence_index')),
    sa.UniqueConstraint('run_id', 'artifact_path', name='uq_evidence_run_artifact_path')
    )
    op.create_index('ix_evidence_run_created', 'evidence_index', ['run_id', 'created_at_us'], unique=False)
    op.create_table('finding_occurrences',
    sa.Column('occurrence_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('evidence_refs_json', sa.Text(), nullable=False),
    sa.Column('object_context_json', sa.Text(), nullable=False),
    sa.Column('coverage_context_json', sa.Text(), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("length(occurrence_id) = 36 AND substr(occurrence_id, 1, 4) = 'occ_' AND substr(occurrence_id, 5) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_finding_occurrences_occurrence_id_format')),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical', 'unknown')", name=op.f('ck_finding_occurrences_occurrence_severity_value')),
    sa.CheckConstraint("status IN ('APPEARED', 'PRESENT', 'DISAPPEARED', 'REAPPEARED', 'CHANGED')", name=op.f('ck_finding_occurrences_occurrence_status_value')),
    sa.CheckConstraint("verdict IN ('SAFE', 'VULNERABLE', 'INCONCLUSIVE')", name=op.f('ck_finding_occurrences_occurrence_verdict_value')),
    sa.CheckConstraint('created_at_us >= 0', name=op.f('ck_finding_occurrences_occurrence_created_nonnegative')),
    sa.CheckConstraint('length(coverage_context_json) BETWEEN 2 AND 16384', name=op.f('ck_finding_occurrences_occurrence_coverage_context_length')),
    sa.CheckConstraint('length(evidence_refs_json) BETWEEN 1 AND 16384', name=op.f('ck_finding_occurrences_occurrence_evidence_refs_length')),
    sa.CheckConstraint('length(object_context_json) BETWEEN 2 AND 16384', name=op.f('ck_finding_occurrences_occurrence_object_context_length')),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], name=op.f('fk_finding_occurrences_finding_id_findings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_finding_occurrences_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_finding_occurrences_run_id_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('occurrence_id', name=op.f('pk_finding_occurrences')),
    sa.UniqueConstraint('finding_id', 'run_id', name='uq_finding_occurrence_finding_run')
    )
    op.create_index('ix_finding_occurrences_finding_created', 'finding_occurrences', ['finding_id', 'created_at_us'], unique=False)
    op.create_index('ix_finding_occurrences_run_created', 'finding_occurrences', ['run_id', 'created_at_us'], unique=False)
    op.create_table('flow_draft_revisions',
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.String(length=64), nullable=False),
    sa.Column('draft_json', sa.Text(), nullable=False),
    sa.Column('draft_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("length(draft_sha256) = 64 AND draft_sha256 NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_flow_draft_revisions_draft_sha256_format')),
    sa.CheckConstraint("length(flow_id) BETWEEN 1 AND 64 AND substr(flow_id, 1, 1) GLOB '[a-z]' AND flow_id NOT GLOB '*[^a-z0-9_-]*'", name=op.f('ck_flow_draft_revisions_flow_id_format')),
    sa.CheckConstraint('created_at_us >= 0', name=op.f('ck_flow_draft_revisions_created_nonnegative')),
    sa.CheckConstraint('length(draft_json) BETWEEN 2 AND 4194304', name=op.f('ck_flow_draft_revisions_draft_json_size')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_flow_draft_revisions_revision_positive')),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.recording_id'], name=op.f('fk_flow_draft_revisions_recording_id_recordings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('recording_id', 'revision', name=op.f('pk_flow_draft_revisions'))
    )
    op.create_index('ix_flow_drafts_flow_created', 'flow_draft_revisions', ['flow_id', 'created_at_us'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('recording_id', sa.String(length=36), nullable=True),
    sa.Column('operation_type', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at_us', sa.BigInteger(), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('fencing_token', sa.BigInteger(), nullable=False),
    sa.Column('lease_expires_at_us', sa.BigInteger(), nullable=True),
    sa.Column('cancel_requested_at_us', sa.BigInteger(), nullable=True),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("lease_owner IS NULL OR (length(lease_owner) BETWEEN 1 AND 128 AND lease_owner NOT GLOB '*[^A-Za-z0-9._:-]*')", name=op.f('ck_jobs_lease_owner_format')),
    sa.CheckConstraint("length(job_id) = 36 AND substr(job_id, 1, 4) = 'job_' AND substr(job_id, 5) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_jobs_job_id_format')),
    sa.CheckConstraint("length(operation_type) BETWEEN 1 AND 64 AND operation_type NOT GLOB '*[^A-Z0-9_]*'", name=op.f('ck_jobs_operation_type_format')),
    sa.CheckConstraint("length(request_hash) = 64 AND request_hash NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_jobs_request_hash_format')),
    sa.CheckConstraint("state <> 'RUNNING' OR (lease_owner IS NOT NULL AND fencing_token > 0 AND lease_expires_at_us IS NOT NULL)", name=op.f('ck_jobs_running_lease_required')),
    sa.CheckConstraint("state IN ('PENDING', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED', 'CANCELLED')", name=op.f('ck_jobs_state_value')),
    sa.CheckConstraint('(attempt = 0 AND fencing_token = 0 AND lease_owner IS NULL AND lease_expires_at_us IS NULL) OR (attempt > 0 AND fencing_token > 0)', name=op.f('ck_jobs_attempt_fencing_relation')),
    sa.CheckConstraint('(lease_owner IS NULL AND lease_expires_at_us IS NULL) OR (lease_owner IS NOT NULL AND lease_expires_at_us IS NOT NULL)', name=op.f('ck_jobs_lease_pair')),
    sa.CheckConstraint('(run_id IS NOT NULL AND recording_id IS NULL) OR (run_id IS NULL AND recording_id IS NOT NULL)', name=op.f('ck_jobs_exactly_one_target')),
    sa.CheckConstraint('attempt >= 0 AND max_attempts >= 1 AND attempt <= max_attempts', name=op.f('ck_jobs_attempt_bounds')),
    sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us AND available_at_us >= 0 AND (lease_expires_at_us IS NULL OR lease_expires_at_us >= 0) AND (cancel_requested_at_us IS NULL OR cancel_requested_at_us >= created_at_us)', name=op.f('ck_jobs_time_bounds')),
    sa.CheckConstraint('fencing_token >= 0', name=op.f('ck_jobs_fencing_nonnegative')),
    sa.CheckConstraint('length(idempotency_key) BETWEEN 1 AND 128', name=op.f('ck_jobs_idempotency_key_length')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_jobs_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.recording_id'], name=op.f('fk_jobs_recording_id_recordings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_jobs_run_id_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('project_id', 'operation_type', 'idempotency_key', name='uq_jobs_idempotency_scope'),
    sa.UniqueConstraint('recording_id', name='uq_jobs_recording_id'),
    sa.UniqueConstraint('run_id', name='uq_jobs_run_id')
    )
    op.create_index('ix_jobs_state_available', 'jobs', ['state', 'available_at_us'], unique=False)
    op.create_index('ix_jobs_state_lease_expires', 'jobs', ['state', 'lease_expires_at_us'], unique=False)
    op.create_table('permission_intent_revisions',
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('effective_state', sa.String(length=16), nullable=False),
    sa.Column('subject_actor_id', sa.String(length=36), nullable=False),
    sa.Column('subject_actor_revision', sa.Integer(), nullable=False),
    sa.Column('business_action_id', sa.String(length=36), nullable=False),
    sa.Column('action_revision', sa.Integer(), nullable=False),
    sa.Column('resource_owner_actor_id', sa.String(length=36), nullable=False),
    sa.Column('resource_owner_actor_revision', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('expectation', sa.String(length=8), nullable=False),
    sa.Column('protected_effect_ids_json', sa.Text(), nullable=False),
    sa.Column('intent_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_epoch', sa.Integer(), nullable=False),
    sa.Column('approval_json', sa.Text(), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("effective_state IN ('ACTIVE', 'RETIRED')", name=op.f('ck_permission_intent_revisions_effective_state_value')),
    sa.CheckConstraint("expectation IN ('ALLOW', 'DENY')", name=op.f('ck_permission_intent_revisions_expectation_value')),
    sa.CheckConstraint("relation IN ('OWNS', 'SAME_ROLE_OTHER_ACCOUNT', 'OTHER_ROLE')", name=op.f('ck_permission_intent_revisions_relation_value')),
    sa.CheckConstraint('policy_epoch >= 1', name=op.f('ck_permission_intent_revisions_policy_epoch_positive')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_permission_intent_revisions_revision_positive')),
    sa.ForeignKeyConstraint(['business_action_id', 'action_revision'], ['business_action_revisions.action_id', 'business_action_revisions.revision'], name=op.f('fk_permission_intent_revisions_business_action_id_business_action_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_permission_intent_revisions_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_owner_actor_id', 'resource_owner_actor_revision'], ['business_actor_revisions.actor_id', 'business_actor_revisions.revision'], name=op.f('fk_permission_intent_revisions_resource_owner_actor_id_business_actor_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_actor_id', 'subject_actor_revision'], ['business_actor_revisions.actor_id', 'business_actor_revisions.revision'], name=op.f('fk_permission_intent_revisions_subject_actor_id_business_actor_revisions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('intent_id', 'revision', name=op.f('pk_permission_intent_revisions'))
    )
    op.create_index('ix_permission_intent_revisions_action', 'permission_intent_revisions', ['business_action_id', 'action_revision'], unique=False)
    op.create_index('ix_permission_intent_revisions_project', 'permission_intent_revisions', ['project_id', 'created_at_us'], unique=False)
    op.create_table('regression_baselines',
    sa.Column('baseline_id', sa.String(length=41), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('accepted_run_id', sa.String(length=36), nullable=False),
    sa.Column('finding_refs_json', sa.Text(), nullable=False),
    sa.Column('coverage_ids_json', sa.Text(), nullable=False),
    sa.Column('coverage_digest', sa.String(length=64), nullable=False),
    sa.Column('request_snapshot_sha256', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('protocol_versions_json', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=1024), nullable=False),
    sa.Column('accepted_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("length(baseline_id) = 41 AND substr(baseline_id, 1, 9) = 'baseline_' AND substr(baseline_id, 10) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_regression_baselines_baseline_id_format')),
    sa.CheckConstraint("length(coverage_digest) = 64 AND coverage_digest NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_regression_baselines_baseline_coverage_digest_format')),
    sa.CheckConstraint("length(request_snapshot_sha256) = 64 AND request_snapshot_sha256 NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_regression_baselines_baseline_snapshot_hash_format')),
    sa.CheckConstraint('accepted_at_us >= 0', name=op.f('ck_regression_baselines_baseline_accepted_nonnegative')),
    sa.CheckConstraint('length(actor) BETWEEN 1 AND 128', name=op.f('ck_regression_baselines_baseline_actor_length')),
    sa.CheckConstraint('length(coverage_ids_json) BETWEEN 2 AND 524288', name=op.f('ck_regression_baselines_baseline_coverage_ids_length')),
    sa.CheckConstraint('length(finding_refs_json) BETWEEN 2 AND 524288', name=op.f('ck_regression_baselines_baseline_finding_refs_length')),
    sa.CheckConstraint('length(protocol_versions_json) BETWEEN 3 AND 4096', name=op.f('ck_regression_baselines_baseline_protocol_versions_length')),
    sa.CheckConstraint('length(reason) BETWEEN 1 AND 1024', name=op.f('ck_regression_baselines_baseline_reason_length')),
    sa.ForeignKeyConstraint(['accepted_run_id'], ['runs.run_id'], name=op.f('fk_regression_baselines_accepted_run_id_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_regression_baselines_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('baseline_id', name=op.f('pk_regression_baselines'))
    )
    op.create_index('ix_regression_baselines_project_accepted', 'regression_baselines', ['project_id', 'accepted_at_us'], unique=False)
    op.create_table('run_finalizations',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('publication_sha256', sa.String(length=64), nullable=False),
    sa.Column('findings_state', sa.String(length=16), nullable=False),
    sa.Column('findings_attempt', sa.Integer(), nullable=False),
    sa.Column('findings_error_code', sa.String(length=64), nullable=True),
    sa.Column('findings_snapshot_sha256', sa.String(length=64), nullable=True),
    sa.Column('findings_completed_at_us', sa.BigInteger(), nullable=True),
    sa.Column('blocked_by_run_id', sa.String(length=36), nullable=True),
    sa.Column('base_report_state', sa.String(length=16), nullable=False),
    sa.Column('base_report_attempt', sa.Integer(), nullable=False),
    sa.Column('base_report_error_code', sa.String(length=64), nullable=True),
    sa.Column('base_report_input_sha256', sa.String(length=64), nullable=True),
    sa.Column('base_report_id', sa.String(length=39), nullable=True),
    sa.Column('base_report_completed_at_us', sa.BigInteger(), nullable=True),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("(base_report_state = 'COMPLETE' AND base_report_input_sha256 IS NOT NULL AND base_report_id IS NOT NULL AND base_report_completed_at_us IS NOT NULL AND base_report_error_code IS NULL) OR (base_report_state = 'FAILED' AND base_report_error_code IS NOT NULL AND base_report_input_sha256 IS NULL AND base_report_id IS NULL AND base_report_completed_at_us IS NULL) OR (base_report_state IN ('BLOCKED', 'PENDING', 'RUNNING') AND base_report_error_code IS NULL AND base_report_input_sha256 IS NULL AND base_report_id IS NULL AND base_report_completed_at_us IS NULL)", name=op.f('ck_run_finalizations_base_report_state_fields_matrix')),
    sa.CheckConstraint("(findings_state = 'COMPLETE' AND findings_snapshot_sha256 IS NOT NULL AND findings_completed_at_us IS NOT NULL AND findings_error_code IS NULL AND blocked_by_run_id IS NULL) OR (findings_state = 'FAILED' AND findings_error_code IS NOT NULL AND findings_snapshot_sha256 IS NULL AND findings_completed_at_us IS NULL AND blocked_by_run_id IS NULL) OR (findings_state = 'BLOCKED' AND blocked_by_run_id IS NOT NULL AND findings_error_code = 'RESULT_FINALIZATION_BLOCKED' AND findings_snapshot_sha256 IS NULL AND findings_completed_at_us IS NULL) OR (findings_state IN ('PENDING', 'RUNNING') AND findings_error_code IS NULL AND findings_snapshot_sha256 IS NULL AND findings_completed_at_us IS NULL AND blocked_by_run_id IS NULL)", name=op.f('ck_run_finalizations_findings_state_fields_matrix')),
    sa.CheckConstraint("base_report_id IS NULL OR (length(base_report_id) = 39 AND substr(base_report_id, 1, 7) = 'report_' AND substr(base_report_id, 8) NOT GLOB '*[^0-9a-f]*')", name=op.f('ck_run_finalizations_base_report_id_format')),
    sa.CheckConstraint("base_report_input_sha256 IS NULL OR (length(base_report_input_sha256) = 64 AND base_report_input_sha256 NOT GLOB '*[^0-9a-f]*')", name=op.f('ck_run_finalizations_base_report_input_sha256_format')),
    sa.CheckConstraint("base_report_state IN ('BLOCKED', 'PENDING', 'RUNNING', 'COMPLETE', 'FAILED')", name=op.f('ck_run_finalizations_base_report_state_value')),
    sa.CheckConstraint("findings_snapshot_sha256 IS NULL OR (length(findings_snapshot_sha256) = 64 AND findings_snapshot_sha256 NOT GLOB '*[^0-9a-f]*')", name=op.f('ck_run_finalizations_findings_snapshot_sha256_format')),
    sa.CheckConstraint("findings_state IN ('PENDING', 'RUNNING', 'COMPLETE', 'FAILED', 'BLOCKED')", name=op.f('ck_run_finalizations_findings_state_value')),
    sa.CheckConstraint("length(publication_sha256) = 64 AND publication_sha256 NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_run_finalizations_publication_sha256_format')),
    sa.CheckConstraint('base_report_completed_at_us IS NULL OR base_report_completed_at_us >= 0', name=op.f('ck_run_finalizations_base_report_completed_at_nonnegative')),
    sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_run_finalizations_time_order')),
    sa.CheckConstraint('findings_attempt >= 0 AND base_report_attempt >= 0', name=op.f('ck_run_finalizations_attempt_nonnegative')),
    sa.CheckConstraint('findings_completed_at_us IS NULL OR findings_completed_at_us >= 0', name=op.f('ck_run_finalizations_findings_completed_at_nonnegative')),
    sa.ForeignKeyConstraint(['blocked_by_run_id'], ['runs.run_id'], name=op.f('fk_run_finalizations_blocked_by_run_id_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_run_finalizations_run_id_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_run_finalizations'))
    )
    op.create_index('ix_run_finalizations_base_report_state', 'run_finalizations', ['base_report_state', 'updated_at_us'], unique=False)
    op.create_index('ix_run_finalizations_findings_state', 'run_finalizations', ['findings_state', 'updated_at_us'], unique=False)
    op.create_table('source_change_sets',
    sa.Column('change_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('previous_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('current_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('added_paths_json', sa.Text(), nullable=False),
    sa.Column('modified_paths_json', sa.Text(), nullable=False),
    sa.Column('removed_paths_json', sa.Text(), nullable=False),
    sa.Column('change_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("status IN ('COMPARABLE', 'NO_BASELINE')", name=op.f('ck_source_change_sets_status_value')),
    sa.CheckConstraint('created_at_us >= 0', name=op.f('ck_source_change_sets_created_nonnegative')),
    sa.CheckConstraint('length(added_paths_json) BETWEEN 2 AND 524288', name=op.f('ck_source_change_sets_added_json_length')),
    sa.CheckConstraint('length(change_fingerprint) = 64', name=op.f('ck_source_change_sets_fingerprint_length')),
    sa.CheckConstraint('length(modified_paths_json) BETWEEN 2 AND 524288', name=op.f('ck_source_change_sets_modified_json_length')),
    sa.CheckConstraint('length(removed_paths_json) BETWEEN 2 AND 524288', name=op.f('ck_source_change_sets_removed_json_length')),
    sa.ForeignKeyConstraint(['change_id'], ['change_manifests.change_id'], name=op.f('fk_source_change_sets_change_id_change_manifests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_snapshot_id'], ['source_revision_snapshots.snapshot_id'], name=op.f('fk_source_change_sets_current_snapshot_id_source_revision_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['source_revision_snapshots.snapshot_id'], name=op.f('fk_source_change_sets_previous_snapshot_id_source_revision_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_source_change_sets_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('change_id', name=op.f('pk_source_change_sets'))
    )
    op.create_table('test_identities',
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('actor_revision', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('auth_method', sa.String(length=32), nullable=True),
    sa.Column('bearer_secret_ref', sa.String(length=512), nullable=True),
    sa.Column('prepared_at_us', sa.BigInteger(), nullable=True),
    sa.Column('refreshed_at_us', sa.BigInteger(), nullable=True),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("auth_method IS NULL OR auth_method IN ('COOKIE_SESSION', 'BEARER')", name=op.f('ck_test_identities_test_identity_auth_method_value')),
    sa.CheckConstraint("length(identity_id) = 36 AND identity_id GLOB 'tid_[0-9a-f]*'", name=op.f('ck_test_identities_test_identity_id_format')),
    sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_test_identities_test_identity_time_order')),
    sa.ForeignKeyConstraint(['actor_id', 'actor_revision'], ['business_actor_revisions.actor_id', 'business_actor_revisions.revision'], name=op.f('fk_test_identities_actor_id_business_actor_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_test_identities_project_id_projects')),
    sa.PrimaryKeyConstraint('identity_id', name=op.f('pk_test_identities'))
    )
    op.create_index('ix_test_identities_project_updated', 'test_identities', ['project_id', 'updated_at_us'], unique=False)
    op.create_table('gate_results',
    sa.Column('gate_result_id', sa.String(length=37), nullable=False),
    sa.Column('baseline_id', sa.String(length=41), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('policy_version', sa.String(length=16), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=False),
    sa.Column('decision', sa.String(length=8), nullable=False),
    sa.Column('evaluated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("decision IN ('PASS', 'BLOCK', 'ERROR')", name=op.f('ck_gate_results_gate_result_decision_value')),
    sa.CheckConstraint("length(gate_result_id) = 37 AND substr(gate_result_id, 1, 5) = 'gate_' AND substr(gate_result_id, 6) NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_gate_results_gate_result_id_format')),
    sa.CheckConstraint("length(input_hash) = 64 AND input_hash NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_gate_results_gate_result_input_hash_format')),
    sa.CheckConstraint("policy_version = 'gate-v1'", name=op.f('ck_gate_results_gate_result_policy_version_value')),
    sa.CheckConstraint('evaluated_at_us >= 0', name=op.f('ck_gate_results_gate_result_evaluated_nonnegative')),
    sa.CheckConstraint('length(reasons_json) BETWEEN 2 AND 524288', name=op.f('ck_gate_results_gate_result_reasons_length')),
    sa.ForeignKeyConstraint(['baseline_id'], ['regression_baselines.baseline_id'], name=op.f('fk_gate_results_baseline_id_regression_baselines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_gate_results_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_gate_results_run_id_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('gate_result_id', name=op.f('pk_gate_results')),
    sa.UniqueConstraint('baseline_id', 'run_id', 'policy_version', 'input_hash', name='uq_gate_result_input')
    )
    op.create_index('ix_gate_results_baseline_run', 'gate_results', ['baseline_id', 'run_id', 'evaluated_at_us'], unique=False)
    op.create_table('job_events',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source_state', sa.String(length=16), nullable=True),
    sa.Column('target_state', sa.String(length=16), nullable=True),
    sa.Column('occurred_at_us', sa.BigInteger(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.CheckConstraint("length(event_type) BETWEEN 1 AND 64 AND event_type NOT GLOB '*[^A-Z0-9_]*'", name=op.f('ck_job_events_event_type_format')),
    sa.CheckConstraint("source_state IS NULL OR source_state IN ('PENDING', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED', 'CANCELLED')", name=op.f('ck_job_events_source_state_value')),
    sa.CheckConstraint("target_state IS NULL OR target_state IN ('PENDING', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED', 'CANCELLED')", name=op.f('ck_job_events_target_state_value')),
    sa.CheckConstraint('length(metadata_json) BETWEEN 2 AND 4096', name=op.f('ck_job_events_metadata_length')),
    sa.CheckConstraint('occurred_at_us >= 0', name=op.f('ck_job_events_occurred_nonnegative')),
    sa.CheckConstraint('sequence >= 1', name=op.f('ck_job_events_sequence_positive')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], name=op.f('fk_job_events_job_id_jobs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('job_id', 'sequence', name=op.f('pk_job_events'))
    )
    op.create_index('ix_job_events_job_occurred', 'job_events', ['job_id', 'occurred_at_us'], unique=False)
    op.create_table('test_identity_cookies',
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('secure', sa.Boolean(), nullable=False),
    sa.Column('http_only', sa.Boolean(), nullable=False),
    sa.Column('same_site', sa.String(length=8), nullable=False),
    sa.Column('expires_at_us', sa.BigInteger(), nullable=True),
    sa.Column('value_secret_ref', sa.String(length=512), nullable=False),
    sa.CheckConstraint('ordinal BETWEEN 0 AND 31', name=op.f('ck_test_identity_cookies_test_identity_cookie_ordinal')),
    sa.ForeignKeyConstraint(['identity_id'], ['test_identities.identity_id'], name=op.f('fk_test_identity_cookies_identity_id_test_identities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_id', 'ordinal', name=op.f('pk_test_identity_cookies')),
    sa.UniqueConstraint('identity_id', 'name', 'domain', 'path', name='uq_test_identity_cookie')
    )
    op.create_table('test_resources',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('action_candidate_id', sa.String(length=39), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('flow_id', sa.String(length=64), nullable=False),
    sa.Column('logical_name', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=False),
    sa.Column('actual_resource_id', sa.String(length=256), nullable=False),
    sa.Column('owner_test_identity_id', sa.String(length=36), nullable=False),
    sa.Column('owner_role_candidate_id', sa.String(length=37), nullable=False),
    sa.Column('relation', sa.String(length=16), nullable=False),
    sa.Column('consumer', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=512), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('endpoint_source_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('understanding_revision', sa.Integer(), nullable=False),
    sa.Column('flow_sha256', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at_us', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("consumer IN ('PATH', 'QUERY', 'JSON_BODY')", name=op.f('ck_test_resources_test_resource_consumer_value')),
    sa.CheckConstraint("length(resource_id) = 36 AND resource_id GLOB 'trs_[0-9a-f]*'", name=op.f('ck_test_resources_test_resource_id_format')),
    sa.CheckConstraint("relation = 'OWNS'", name=op.f('ck_test_resources_test_resource_relation_value')),
    sa.CheckConstraint('created_at_us >= 0 AND updated_at_us >= created_at_us', name=op.f('ck_test_resources_test_resource_time_order')),
    sa.ForeignKeyConstraint(['owner_test_identity_id'], ['test_identities.identity_id'], name=op.f('fk_test_resources_owner_test_identity_id_test_identities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_test_resources_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.recording_id'], name=op.f('fk_test_resources_recording_id_recordings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', name=op.f('pk_test_resources')),
    sa.UniqueConstraint('project_id', 'action_candidate_id', name='uq_test_resource_project_action')
    )
    op.create_index('ix_test_resources_recording', 'test_resources', ['recording_id'], unique=False)
    op.create_table('observation_bindings',
    sa.Column('observation_binding_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('trusted_test_identity_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('source_step_id', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path_template', sa.String(length=8192), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("kind = 'OWNER_READ' AND method = 'GET' AND required = 1", name=op.f('ck_observation_bindings_observation_binding_value')),
    sa.CheckConstraint("length(observation_binding_id) = 36 AND observation_binding_id GLOB 'obs_[0-9a-f]*'", name=op.f('ck_observation_bindings_observation_binding_id_format')),
    sa.ForeignKeyConstraint(['resource_id'], ['test_resources.resource_id'], name=op.f('fk_observation_bindings_resource_id_test_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trusted_test_identity_id'], ['test_identities.identity_id'], name=op.f('fk_observation_bindings_trusted_test_identity_id_test_identities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('observation_binding_id', name=op.f('pk_observation_bindings')),
    sa.UniqueConstraint('resource_id', name='uq_observation_binding_resource')
    )
    op.create_table('recovery_bindings',
    sa.Column('recovery_binding_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('test_identity_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('source_step_id', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=True),
    sa.Column('path_template', sa.String(length=8192), nullable=True),
    sa.Column('json_body_template', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("(kind = 'NOT_REQUIRED' AND source_step_id IS NULL AND method IS NULL AND path_template IS NULL AND json_body_template = '{}') OR (kind = 'RECORDED_REQUEST' AND source_step_id IS NOT NULL AND method IN ('PATCH', 'POST', 'PUT', 'DELETE') AND path_template IS NOT NULL)", name=op.f('ck_recovery_bindings_recovery_binding_request_shape')),
    sa.CheckConstraint("kind IN ('RECORDED_REQUEST', 'NOT_REQUIRED')", name=op.f('ck_recovery_bindings_recovery_binding_kind_value')),
    sa.CheckConstraint("length(recovery_binding_id) = 36 AND recovery_binding_id GLOB 'rcv_[0-9a-f]*'", name=op.f('ck_recovery_bindings_recovery_binding_id_format')),
    sa.ForeignKeyConstraint(['resource_id'], ['test_resources.resource_id'], name=op.f('fk_recovery_bindings_resource_id_test_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_identity_id'], ['test_identities.identity_id'], name=op.f('fk_recovery_bindings_test_identity_id_test_identities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recovery_binding_id', name=op.f('pk_recovery_bindings')),
    sa.UniqueConstraint('resource_id', name='uq_recovery_binding_resource')
    )
    op.create_table('security_effect_confirmations',
    sa.Column('effect_confirmation_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('action_candidate_id', sa.String(length=39), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('protected_fields', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at_us', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("length(effect_confirmation_id) = 36 AND effect_confirmation_id GLOB 'efc_[0-9a-f]*'", name=op.f('ck_security_effect_confirmations_effect_confirmation_id_format')),
    sa.ForeignKeyConstraint(['resource_id'], ['test_resources.resource_id'], name=op.f('fk_security_effect_confirmations_resource_id_test_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('effect_confirmation_id', name=op.f('pk_security_effect_confirmations')),
    sa.UniqueConstraint('resource_id', name='uq_effect_confirmation_resource')
    )
    # Project 双字段绑定约束依赖 SQLite trigger；它属于完整基线而不是运行时补表。
    op.execute(
        "CREATE TRIGGER projects_governed_binding_insert "
        "BEFORE INSERT ON projects BEGIN "
        "SELECT RAISE(ABORT, 'governed contract binding must be paired') "
        "WHERE (NEW.governed_contract_id IS NULL) != "
        "(NEW.governed_contract_version IS NULL) "
        "OR (NEW.governed_contract_version IS NOT NULL "
        "AND NEW.governed_contract_version < 1); END"
    )
    op.execute(
        "CREATE TRIGGER projects_governed_binding_update "
        "BEFORE UPDATE OF governed_contract_id, governed_contract_version "
        "ON projects BEGIN "
        "SELECT RAISE(ABORT, 'governed contract binding must be paired') "
        "WHERE (NEW.governed_contract_id IS NULL) != "
        "(NEW.governed_contract_version IS NULL) "
        "OR (NEW.governed_contract_version IS NOT NULL "
        "AND NEW.governed_contract_version < 1); END"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS projects_governed_binding_update")
    op.execute("DROP TRIGGER IF EXISTS projects_governed_binding_insert")
    op.drop_table('security_effect_confirmations')
    op.drop_table('recovery_bindings')
    op.drop_table('observation_bindings')
    op.drop_index('ix_test_resources_recording', table_name='test_resources')
    op.drop_table('test_resources')
    op.drop_table('test_identity_cookies')
    op.drop_index('ix_job_events_job_occurred', table_name='job_events')
    op.drop_table('job_events')
    op.drop_index('ix_gate_results_baseline_run', table_name='gate_results')
    op.drop_table('gate_results')
    op.drop_index('ix_test_identities_project_updated', table_name='test_identities')
    op.drop_table('test_identities')
    op.drop_table('source_change_sets')
    op.drop_index('ix_run_finalizations_findings_state', table_name='run_finalizations')
    op.drop_index('ix_run_finalizations_base_report_state', table_name='run_finalizations')
    op.drop_table('run_finalizations')
    op.drop_index('ix_regression_baselines_project_accepted', table_name='regression_baselines')
    op.drop_table('regression_baselines')
    op.drop_index('ix_permission_intent_revisions_project', table_name='permission_intent_revisions')
    op.drop_index('ix_permission_intent_revisions_action', table_name='permission_intent_revisions')
    op.drop_table('permission_intent_revisions')
    op.drop_index('ix_jobs_state_lease_expires', table_name='jobs')
    op.drop_index('ix_jobs_state_available', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_flow_drafts_flow_created', table_name='flow_draft_revisions')
    op.drop_table('flow_draft_revisions')
    op.drop_index('ix_finding_occurrences_run_created', table_name='finding_occurrences')
    op.drop_index('ix_finding_occurrences_finding_created', table_name='finding_occurrences')
    op.drop_table('finding_occurrences')
    op.drop_index('ix_evidence_run_created', table_name='evidence_index')
    op.drop_table('evidence_index')
    op.drop_index('ix_change_impacts_project_created', table_name='change_impact_assessments')
    op.drop_table('change_impact_assessments')
    op.drop_index('ix_business_actors_project', table_name='business_actors')
    op.drop_table('business_actors')
    op.drop_index('ix_business_actions_project', table_name='business_actions')
    op.drop_table('business_actions')
    op.drop_table('boundary_proposal_decisions')
    op.drop_table('actor_implementation_bindings')
    op.drop_table('action_implementation_bindings')
    op.drop_index('ix_source_revision_project_created', table_name='source_revision_snapshots')
    op.drop_table('source_revision_snapshots')
    op.drop_index('ix_runs_project_created', table_name='runs')
    op.drop_index('ix_runs_lifecycle_updated', table_name='runs')
    op.drop_table('runs')
    op.drop_index('ix_recordings_state_updated', table_name='recordings')
    op.drop_index('ix_recordings_project_created', table_name='recordings')
    op.drop_index('ix_recordings_parent_purpose', table_name='recordings')
    op.drop_table('recordings')
    op.drop_table('project_policy_states')
    op.drop_index('ix_findings_project_updated', table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_permission_profiles_project_updated', table_name='execution_profiles')
    op.drop_table('execution_profiles')
    op.drop_index('uq_contract_versions_active', table_name='contract_versions', sqlite_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('ix_contract_versions_project_status', table_name='contract_versions')
    op.drop_table('contract_versions')
    op.drop_index('ix_change_manifests_project_created', table_name='change_manifests')
    op.drop_table('change_manifests')
    op.drop_index('ix_business_actor_revisions_project', table_name='business_actor_revisions')
    op.drop_table('business_actor_revisions')
    op.drop_index('ix_business_action_revisions_project', table_name='business_action_revisions')
    op.drop_table('business_action_revisions')
    op.drop_index('ix_boundary_proposals_project', table_name='boundary_proposals')
    op.drop_table('boundary_proposals')
    op.drop_index('ix_application_understanding_updated', table_name='application_understanding')
    op.drop_table('application_understanding')
    op.drop_table('ai_assistance_settings')
    op.drop_index('ix_projects_status_updated', table_name='projects')
    op.drop_table('projects')
    op.drop_table('llm_profiles')
    # ### end Alembic commands ###
