# =============================================================================
# 稳定错误模型
#
# 定位
#   领域、应用、CLI 与 API 共享的脱敏错误代码边界
#
# 职责
#   定义稳定 ErrorCode｜保存安全详情｜在构造时统一脱敏
#
# 调用链
#   Domain / Application / Infrastructure → JiejianError → CLI / API mapping
# =============================================================================

from __future__ import annotations

from enum import StrEnum
from typing import Any, Mapping

from .redaction import redact


class ErrorCode(StrEnum):
    CFG_FILE = "CFG_FILE"
    CFG_INVALID = "CFG_INVALID"
    INPUT_FILE = "INPUT_FILE"
    INPUT_INVALID = "INPUT_INVALID"
    INPUT_PATH = "INPUT_PATH"
    SCOPE_URL = "SCOPE_URL"
    SCOPE_HOST = "SCOPE_HOST"
    SCOPE_PORT = "SCOPE_PORT"
    SCOPE_PRIVATE_NETWORK = "SCOPE_PRIVATE_NETWORK"
    SCOPE_REDIRECT = "SCOPE_REDIRECT"
    SECRET_MISSING = "SECRET_MISSING"
    EXEC_REQUEST = "EXEC_REQUEST"
    EXEC_TIMEOUT = "EXEC_TIMEOUT"
    EXEC_CANCELLED = "EXEC_CANCELLED"
    EXEC_BUDGET = "EXEC_BUDGET"
    EXEC_RESPONSE_TOO_LARGE = "EXEC_RESPONSE_TOO_LARGE"
    ARTIFACT_WRITE = "ARTIFACT_WRITE"
    ARTIFACT_PUBLISH = "ARTIFACT_PUBLISH"
    ARTIFACT_FENCE = "ARTIFACT_FENCE"
    ARTIFACT_MANIFEST = "ARTIFACT_MANIFEST"
    ARTIFACT_RECONCILE = "ARTIFACT_RECONCILE"
    REPORT_NOT_FOUND = "REPORT_NOT_FOUND"
    STORAGE_CONSTRAINT = "STORAGE_CONSTRAINT"
    STORAGE_FAILURE = "STORAGE_FAILURE"
    STORAGE_MIGRATION = "STORAGE_MIGRATION"
    STORAGE_SECRET = "STORAGE_SECRET"
    STORAGE_STATE = "STORAGE_STATE"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_IDEMPOTENCY_CONFLICT = "JOB_IDEMPOTENCY_CONFLICT"
    JOB_NOT_CLAIMABLE = "JOB_NOT_CLAIMABLE"
    JOB_LEASE_MISMATCH = "JOB_LEASE_MISMATCH"
    JOB_LEASE_EXPIRED = "JOB_LEASE_EXPIRED"
    JOB_RECOVERY_REQUIRED = "JOB_RECOVERY_REQUIRED"
    JOB_CANCEL_CONFLICT = "JOB_CANCEL_CONFLICT"
    JOB_TERMINAL_CONFLICT = "JOB_TERMINAL_CONFLICT"
    JOB_ATTEMPTS_EXHAUSTED = "JOB_ATTEMPTS_EXHAUSTED"
    JOB_RETRY_POLICY_INVALID = "JOB_RETRY_POLICY_INVALID"
    JOB_SECRET = "JOB_SECRET"
    JOB_PERSISTENCE = "JOB_PERSISTENCE"
    JOB_TIME_INVALID = "JOB_TIME_INVALID"
    JOB_REQUEST_MISSING = "JOB_REQUEST_MISSING"
    JOB_REQUEST_CONFLICT = "JOB_REQUEST_CONFLICT"
    RUNNER_START_FAILED = "RUNNER_START_FAILED"
    RUNNER_TIMEOUT = "RUNNER_TIMEOUT"
    RUNNER_PROTOCOL_INVALID = "RUNNER_PROTOCOL_INVALID"
    RUNNER_RESULT_MISSING = "RUNNER_RESULT_MISSING"
    RECORD_PROTOCOL_INVALID = "RECORD_PROTOCOL_INVALID"
    RECORD_PROTOCOL_TOO_LARGE = "RECORD_PROTOCOL_TOO_LARGE"
    RECORD_SECRET_EXPOSED = "RECORD_SECRET_EXPOSED"
    RECORD_STATE_INVALID = "RECORD_STATE_INVALID"
    RECORD_STATE_PRECONDITION = "RECORD_STATE_PRECONDITION"
    RECORD_BROWSER_START_FAILED = "RECORD_BROWSER_START_FAILED"
    RECORD_INTERACTION_FAILED = "RECORD_INTERACTION_FAILED"
    RECORD_EVENT_BUDGET = "RECORD_EVENT_BUDGET"
    RECORD_SCOPE_BLOCKED = "RECORD_SCOPE_BLOCKED"
    RECORD_SESSION_EXPIRED = "RECORD_SESSION_EXPIRED"
    RECORD_RESPONSE_UNSUPPORTED = "RECORD_RESPONSE_UNSUPPORTED"
    RECORD_CANCELLED = "RECORD_CANCELLED"
    RECORD_CLEANUP_FAILED = "RECORD_CLEANUP_FAILED"
    RECORD_DRAFT_INVALID = "RECORD_DRAFT_INVALID"
    RECORD_DRAFT_REFERENCE = "RECORD_DRAFT_REFERENCE"
    RECORD_DRAFT_NOT_ADJACENT = "RECORD_DRAFT_NOT_ADJACENT"
    RECORD_DRAFT_MERGE = "RECORD_DRAFT_MERGE"
    RECORD_DRAFT_CYCLE = "RECORD_DRAFT_CYCLE"
    RECORD_DRAFT_UNCONFIRMED = "RECORD_DRAFT_UNCONFIRMED"
    RECORD_DRAFT_COMPILE = "RECORD_DRAFT_COMPILE"
    RECORD_NOT_FOUND = "RECORD_NOT_FOUND"
    RECORD_REVIEW_STATE = "RECORD_REVIEW_STATE"
    RECORD_FLOW_PUBLISH = "RECORD_FLOW_PUBLISH"
    RECORD_REPLAY_FAILED = "RECORD_REPLAY_FAILED"
    STATE_INVALID_ENTITY = "STATE_INVALID_ENTITY"
    STATE_INVALID_TARGET = "STATE_INVALID_TARGET"
    STATE_INVALID_TRANSITION = "STATE_INVALID_TRANSITION"
    STATE_OPERATOR_REQUIRED = "STATE_OPERATOR_REQUIRED"
    STATE_PRECONDITION = "STATE_PRECONDITION"
    CONTRACT_IMMUTABLE = "CONTRACT_IMMUTABLE"
    API_NOT_READY = "API_NOT_READY"
    API_BINDING_REJECTED = "API_BINDING_REJECTED"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    PROJECT_SOURCE_DRIFT = "PROJECT_SOURCE_DRIFT"
    PROJECT_NOT_REVALIDATED = "PROJECT_NOT_REVALIDATED"
    CONTRACT_NOT_FOUND = "CONTRACT_NOT_FOUND"
    CONTRACT_NOT_ACTIVE = "CONTRACT_NOT_ACTIVE"
    CONTRACT_REFERENCE_INVALID = "CONTRACT_REFERENCE_INVALID"
    CONTRACT_ASSESSMENT_BLOCKED = "CONTRACT_ASSESSMENT_BLOCKED"
    CONTRACT_ANALYSIS_INVALID = "CONTRACT_ANALYSIS_INVALID"
    CONTRACT_HISTORY_NOT_FOUND = "CONTRACT_HISTORY_NOT_FOUND"
    CONTRACT_CANDIDATE_CONFLICT = "CONTRACT_CANDIDATE_CONFLICT"
    LLM_PROVIDER_UNAVAILABLE = "LLM_PROVIDER_UNAVAILABLE"
    LLM_PROVIDER_FAILED = "LLM_PROVIDER_FAILED"
    LLM_OUTPUT_INVALID = "LLM_OUTPUT_INVALID"
    LLM_REQUIREMENT_INVALID = "LLM_REQUIREMENT_INVALID"
    ARTIFACT_NOT_PUBLISHED = "ARTIFACT_NOT_PUBLISHED"
    ARTIFACT_HASH_MISMATCH = "ARTIFACT_HASH_MISMATCH"
    SERVE_FAILED = "SERVE_FAILED"
    LLM_AUTH_FAILED = "llm_auth_failed"
    LLM_RATE_LIMITED = "llm_rate_limited"
    LLM_TIMEOUT = "llm_timeout"
    LLM_INVALID_RESPONSE = "llm_invalid_response"
    LLM_BUDGET_EXCEEDED = "llm_budget_exceeded"
    LLM_PROVIDER_UNAVAILABLE_WIRE = "llm_provider_unavailable"
    LLM_PROFILE_NOT_FOUND = "LLM_PROFILE_NOT_FOUND"
    LLM_PROFILE_INVALID = "LLM_PROFILE_INVALID"
    LLM_SECRET_UNAVAILABLE = "LLM_SECRET_UNAVAILABLE"
    LLM_PROFILE_STORAGE_FAILED = "LLM_PROFILE_STORAGE_FAILED"
    LLM_TEST_IN_PROGRESS = "LLM_TEST_IN_PROGRESS"
    PERMISSION_PROFILE_NOT_FOUND = "PERMISSION_PROFILE_NOT_FOUND"
    PERMISSION_PROFILE_SOURCE_DRIFT = "PERMISSION_PROFILE_SOURCE_DRIFT"
    PERMISSION_PROFILE_PROJECT_CONFLICT = "PERMISSION_PROFILE_PROJECT_CONFLICT"
    PERMISSION_PROFILE_INVALID = "PERMISSION_PROFILE_INVALID"
    PERMISSION_PROFILE_STORAGE_FAILED = "PERMISSION_PROFILE_STORAGE_FAILED"
    BASELINE_NOT_FOUND = "BASELINE_NOT_FOUND"
    BASELINE_INVALID = "BASELINE_INVALID"
    BASELINE_IMMUTABLE = "BASELINE_IMMUTABLE"
    GATE_INPUT_INVALID = "GATE_INPUT_INVALID"
    GATE_RESULT_NOT_FOUND = "GATE_RESULT_NOT_FOUND"
    ONBOARDING_INPUT_INVALID = "ONBOARDING_INPUT_INVALID"
    ONBOARDING_PATH_UNSAFE = "ONBOARDING_PATH_UNSAFE"
    ONBOARDING_READ_BUDGET = "ONBOARDING_READ_BUDGET"
    ONBOARDING_SELECTOR_UNAVAILABLE = "ONBOARDING_SELECTOR_UNAVAILABLE"
    ONBOARDING_SESSION_NOT_FOUND = "ONBOARDING_SESSION_NOT_FOUND"
    ONBOARDING_SESSION_CONFLICT = "ONBOARDING_SESSION_CONFLICT"
    ONBOARDING_SESSION_INCOMPLETE = "ONBOARDING_SESSION_INCOMPLETE"
    ONBOARDING_TARGET_INVALID = "ONBOARDING_TARGET_INVALID"
    ONBOARDING_CREDENTIALS_INVALID = "ONBOARDING_CREDENTIALS_INVALID"
    ONBOARDING_BUNDLE_FAILED = "ONBOARDING_BUNDLE_FAILED"
    ONBOARDING_DEMO_FAILED = "ONBOARDING_DEMO_FAILED"


class LLMWireErrorCode(StrEnum):
    """供应商传输边界对外冻结的小写 wire code。"""

    AUTH_FAILED = "llm_auth_failed"
    RATE_LIMITED = "llm_rate_limited"
    TIMEOUT = "llm_timeout"
    INVALID_RESPONSE = "llm_invalid_response"
    BUDGET_EXCEEDED = "llm_budget_exceeded"
    PROVIDER_UNAVAILABLE = "llm_provider_unavailable"


LLM_WIRE_TO_INTERNAL: dict[LLMWireErrorCode, ErrorCode] = {
    LLMWireErrorCode.AUTH_FAILED: ErrorCode.LLM_AUTH_FAILED,
    LLMWireErrorCode.RATE_LIMITED: ErrorCode.LLM_RATE_LIMITED,
    LLMWireErrorCode.TIMEOUT: ErrorCode.LLM_TIMEOUT,
    LLMWireErrorCode.INVALID_RESPONSE: ErrorCode.LLM_INVALID_RESPONSE,
    LLMWireErrorCode.BUDGET_EXCEEDED: ErrorCode.LLM_BUDGET_EXCEEDED,
    LLMWireErrorCode.PROVIDER_UNAVAILABLE: ErrorCode.LLM_PROVIDER_UNAVAILABLE_WIRE,
}


class JiejianError(Exception):
    """具有稳定错误码且可以安全序列化的内部错误。"""

    def __init__(
        self,
        code: ErrorCode | str,
        message: str,
        *,
        details: Mapping[str, Any] | None = None,
    ) -> None:
        self._code = code.value if isinstance(code, ErrorCode) else str(code)
        self._message = message
        self._details = dict(details or {})
        super().__init__(f"{self._code}: {redact(self._message)}")

    @property
    def code(self) -> str:
        return self._code

    def to_dict(self) -> dict[str, Any]:
        return redact(
            {
                "schema_version": "1",
                "code": self._code,
                "message": self._message,
                "details": self._details,
            }
        )
