"""跨 CLI、服务与领域层复用的稳定错误结构。"""

from __future__ import annotations

from enum import StrEnum
from typing import Any, Mapping

from .redaction import redact


class ErrorCode(StrEnum):
    CFG_FILE = "CFG_FILE"
    CFG_INVALID = "CFG_INVALID"
    INPUT_FILE = "INPUT_FILE"
    INPUT_INVALID = "INPUT_INVALID"
    INPUT_PATH = "INPUT_PATH"
    SCOPE_URL = "SCOPE_URL"
    SCOPE_HOST = "SCOPE_HOST"
    SCOPE_PORT = "SCOPE_PORT"
    SCOPE_PRIVATE_NETWORK = "SCOPE_PRIVATE_NETWORK"
    SCOPE_REDIRECT = "SCOPE_REDIRECT"
    SECRET_MISSING = "SECRET_MISSING"
    EXEC_REQUEST = "EXEC_REQUEST"
    EXEC_TIMEOUT = "EXEC_TIMEOUT"
    EXEC_CANCELLED = "EXEC_CANCELLED"
    EXEC_BUDGET = "EXEC_BUDGET"
    EXEC_RESPONSE_TOO_LARGE = "EXEC_RESPONSE_TOO_LARGE"
    ARTIFACT_WRITE = "ARTIFACT_WRITE"
    ARTIFACT_PUBLISH = "ARTIFACT_PUBLISH"
    ARTIFACT_FENCE = "ARTIFACT_FENCE"
    ARTIFACT_MANIFEST = "ARTIFACT_MANIFEST"
    ARTIFACT_RECONCILE = "ARTIFACT_RECONCILE"
    REPORT_NOT_FOUND = "REPORT_NOT_FOUND"
    STORAGE_CONSTRAINT = "STORAGE_CONSTRAINT"
    STORAGE_FAILURE = "STORAGE_FAILURE"
    STORAGE_MIGRATION = "STORAGE_MIGRATION"
    STORAGE_SECRET = "STORAGE_SECRET"
    STORAGE_STATE = "STORAGE_STATE"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_IDEMPOTENCY_CONFLICT = "JOB_IDEMPOTENCY_CONFLICT"
    JOB_NOT_CLAIMABLE = "JOB_NOT_CLAIMABLE"
    JOB_LEASE_MISMATCH = "JOB_LEASE_MISMATCH"
    JOB_LEASE_EXPIRED = "JOB_LEASE_EXPIRED"
    JOB_RECOVERY_REQUIRED = "JOB_RECOVERY_REQUIRED"
    JOB_CANCEL_CONFLICT = "JOB_CANCEL_CONFLICT"
    JOB_TERMINAL_CONFLICT = "JOB_TERMINAL_CONFLICT"
    JOB_ATTEMPTS_EXHAUSTED = "JOB_ATTEMPTS_EXHAUSTED"
    JOB_RETRY_POLICY_INVALID = "JOB_RETRY_POLICY_INVALID"
    JOB_SECRET = "JOB_SECRET"
    JOB_PERSISTENCE = "JOB_PERSISTENCE"
    JOB_TIME_INVALID = "JOB_TIME_INVALID"
    JOB_REQUEST_MISSING = "JOB_REQUEST_MISSING"
    JOB_REQUEST_CONFLICT = "JOB_REQUEST_CONFLICT"
    RUNNER_START_FAILED = "RUNNER_START_FAILED"
    RUNNER_TIMEOUT = "RUNNER_TIMEOUT"
    RUNNER_PROTOCOL_INVALID = "RUNNER_PROTOCOL_INVALID"
    RUNNER_RESULT_MISSING = "RUNNER_RESULT_MISSING"
    RECORD_PROTOCOL_INVALID = "RECORD_PROTOCOL_INVALID"
    RECORD_PROTOCOL_TOO_LARGE = "RECORD_PROTOCOL_TOO_LARGE"
    RECORD_SECRET_EXPOSED = "RECORD_SECRET_EXPOSED"
    RECORD_STATE_INVALID = "RECORD_STATE_INVALID"
    RECORD_STATE_PRECONDITION = "RECORD_STATE_PRECONDITION"
    RECORD_BROWSER_START_FAILED = "RECORD_BROWSER_START_FAILED"
    RECORD_INTERACTION_FAILED = "RECORD_INTERACTION_FAILED"
    RECORD_EVENT_BUDGET = "RECORD_EVENT_BUDGET"
    RECORD_SCOPE_BLOCKED = "RECORD_SCOPE_BLOCKED"
    RECORD_SESSION_EXPIRED = "RECORD_SESSION_EXPIRED"
    RECORD_RESPONSE_UNSUPPORTED = "RECORD_RESPONSE_UNSUPPORTED"
    RECORD_CANCELLED = "RECORD_CANCELLED"
    RECORD_CLEANUP_FAILED = "RECORD_CLEANUP_FAILED"
    RECORD_DRAFT_INVALID = "RECORD_DRAFT_INVALID"
    RECORD_DRAFT_REFERENCE = "RECORD_DRAFT_REFERENCE"
    RECORD_DRAFT_NOT_ADJACENT = "RECORD_DRAFT_NOT_ADJACENT"
    RECORD_DRAFT_MERGE = "RECORD_DRAFT_MERGE"
    RECORD_DRAFT_CYCLE = "RECORD_DRAFT_CYCLE"
    RECORD_DRAFT_UNCONFIRMED = "RECORD_DRAFT_UNCONFIRMED"
    RECORD_DRAFT_COMPILE = "RECORD_DRAFT_COMPILE"
    RECORD_NOT_FOUND = "RECORD_NOT_FOUND"
    RECORD_REVIEW_STATE = "RECORD_REVIEW_STATE"
    RECORD_FLOW_PUBLISH = "RECORD_FLOW_PUBLISH"
    RECORD_REPLAY_FAILED = "RECORD_REPLAY_FAILED"
    STATE_INVALID_ENTITY = "STATE_INVALID_ENTITY"
    STATE_INVALID_TARGET = "STATE_INVALID_TARGET"
    STATE_INVALID_TRANSITION = "STATE_INVALID_TRANSITION"
    STATE_OPERATOR_REQUIRED = "STATE_OPERATOR_REQUIRED"
    STATE_PRECONDITION = "STATE_PRECONDITION"
    CONTRACT_IMMUTABLE = "CONTRACT_IMMUTABLE"


class JiejianError(Exception):
    """具有稳定错误码且可以安全序列化的内部错误。"""

    def __init__(
        self,
        code: ErrorCode | str,
        message: str,
        *,
        details: Mapping[str, Any] | None = None,
    ) -> None:
        self._code = code.value if isinstance(code, ErrorCode) else str(code)
        self._message = message
        self._details = dict(details or {})
        super().__init__(f"{self._code}: {redact(self._message)}")

    @property
    def code(self) -> str:
        return self._code

    def to_dict(self) -> dict[str, Any]:
        return redact(
            {
                "schema_version": "1",
                "code": self._code,
                "message": self._message,
                "details": self._details,
            }
        )
