// 正式动作与角色先只读浏览；只有显式新增或编辑才进入统一草稿工作面。
import { SearchField } from '../../../shared/ui/SearchField'
import { StatusBadge } from '../../../shared/ui/StatusBadge'
import { Button } from 'antd'
import { useState } from 'react'
import type { BusinessBoundaryViewDto } from '../../../api/businessBoundaries'
export type BoundaryEditFocus = { actionId?: string; actorId?: string; intentId?: string; mode?: 'objects' | 'actors' | 'new'; createObject?: boolean; editObject?: boolean }

export function CurrentBoundaryObjects({ boundary, kind, onEdit }: { boundary: BusinessBoundaryViewDto; kind: 'actions' | 'actors'; onEdit: (focus: BoundaryEditFocus) => void }) {
  const [query, setQuery] = useState(''), [selected, setSelected] = useState('')
  const items = kind === 'actions' ? boundary.actions.map(item => ({ id: item.action_id, name: item.display_name, description: item.description, revision: item.revision })) : boundary.actors.map(item => ({ id: item.actor_id, name: item.display_name, description: item.description, revision: item.revision }))
  const current = items.find(item => item.id === selected) ?? items[0]
  const action = kind === 'actions' ? boundary.actions.find(item => item.action_id === current?.id) : undefined
  const permissions = boundary.permission_intents.filter(item => item.effective_state === 'ACTIVE' && (kind === 'actions' ? item.business_action_id === current?.id : item.subject_actor_id === current?.id || item.resource_owner_actor_id === current?.id))
  const subject = kind === 'actions' ? '业务动作' : '业务角色'
  const focus = { mode: kind === 'actions' ? 'objects' as const : 'actors' as const, ...(kind === 'actions' ? { actionId: current?.id } : { actorId: current?.id }) }
  return <><div className="boundary-collection-toolbar"><SearchField aria-label={`搜索${subject}`} placeholder={`搜索${subject}`} allowClear value={query} onChange={event => setQuery(event.target.value)}/><Button type="primary" onClick={() => onEdit({ ...focus, createObject: true })}>新增{subject}</Button></div><section className="boundary-document" aria-label={`已确认的${subject}`}><nav className="action-index" aria-label={`${subject}索引`}><h3>{subject}</h3>{items.filter(item => (item.name + item.description).includes(query.trim())).map(item => <button key={item.id} aria-current={item.id === current?.id ? 'true' : undefined} onClick={() => setSelected(item.id)}>{item.name}<small>已确认 · 修订 {item.revision}</small></button>)}</nav><article className="boundary-action-document">{current ? <><div className="boundary-action-heading"><div><p className="editorial-eyebrow">{subject} · 已确认</p><h2>{current.name}</h2></div><Button onClick={() => onEdit({ ...focus, editObject: true })}>编辑{kind === 'actions' ? '动作' : '角色'}</Button></div><p className="definition-description">{current.description}</p>{action && <section className="definition-effect-summary"><h3>需要观察的业务结果</h3>{action.effect_catalog.map(effect => <div key={effect.effect_id}><strong>{effect.business_label}</strong><p>{effect.description}</p></div>)}</section>}<section className="definition-linked"><h3>关联权限 · {permissions.length}</h3>{permissions.map(rule => <div key={rule.intent_id} className="definition-linked-rule"><StatusBadge kind="rule" className="permission-badge" tone={rule.expectation === 'ALLOW' ? 'success' : 'danger'}>{rule.expectation === 'ALLOW' ? '允许' : '禁止'}</StatusBadge><span>{boundary.actors.find(actor => actor.actor_id === rule.subject_actor_id)?.display_name} · {boundary.actions.find(item => item.action_id === rule.business_action_id)?.display_name}</span></div>)}</section><details className="boundary-secondary"><summary>当前代码定位与关联</summary><p>代码定位与业务规则分别核对；仅重新关联实现不会自动改写权限。</p><Button onClick={() => onEdit(focus)}>管理业务对象与代码关联</Button></details></> : <p>尚无已确认的{subject}。</p>}</article></section></>
}
