// 审阅重排不丢失原始对照、业务定义或换提案后的独立确认。
import { fireEvent,render,screen,within } from '@testing-library/react'
import { expect,it,vi } from 'vitest'
import { BoundaryProposalReview } from './BoundaryProposalReview'
import type { BoundaryProposalViewDto,BoundaryReviewValueDto } from '../../../api/businessBoundaries'
const value:BoundaryReviewValueDto={display_name:'成员导出',description:'规则说明',effective_state:'ACTIVE',resource_concept:null,operation_kind:null,state_changing:null,effects:[],subject:'成员',resource_owner:'负责人',action:'导出项目包',relation:'OTHER_ROLE',expectation:'DENY',protected_effects:['完整项目包形成']}
const data=():BoundaryProposalViewDto=>({proposal:{proposal_id:'p1',project_id:'project',source_snapshot:{},proposal_fingerprint:'a'.repeat(64),created_at_us:1,proposed_permissions:[],proposed_actors:[],proposed_actions:[],unresolved_questions:[],provenance:'公开提案'},decision:null,change_summary:null,review:{basis_state:'COMPLETE',current_state_changed:false,items:[{entity_kind:'ACTOR',item_id:'actor',entity_id:null,basis_revision:null,change_kind:'CREATE',basis_available:true,before:null,after:{...value,expectation:null,relation:null,display_name:'成员定义',description:'只能查看本人的资料'}},{entity_kind:'PERMISSION',item_id:'rule',entity_id:null,basis_revision:null,change_kind:'CREATE',basis_available:true,before:null,after:value}]}} )
const props=()=>({busy:false,onApprove:vi.fn(),onReject:vi.fn(),onReturnToEdit:vi.fn()})
it('新增只呈现拟生效规则，业务定义可展开且不堆空白基线',()=>{render(<BoundaryProposalReview {...props()} proposalView={data()}/>);expect(within(screen.getByRole('region',{name:'本次权限变化'})).getByText('成员导出')).toBeVisible();expect(screen.queryByText('尚未建立这项业务要求')).not.toBeInTheDocument();const definition=screen.getByText('成员定义');expect(definition.closest('details')).not.toHaveAttribute('open');fireEvent.click(screen.getByText(/业务定义变更 · 1 项/));expect(definition.closest('details')).toHaveAttribute('open');expect(screen.getByRole('button',{name:'确认这组业务边界'})).toBeDisabled()})
it('修改保留原始与拟生效对照，切换提案不能沿用勾选',()=>{const p=props(),d=data();d.review!.items=[{...d.review!.items[1],change_kind:'UPDATE',before:{...value,expectation:'ALLOW'}}];const view=render(<BoundaryProposalReview {...p} proposalView={d}/>);expect(screen.getByRole('heading',{name:'原始要求'})).toBeVisible();expect(screen.getByRole('heading',{name:'拟生效要求'})).toBeVisible();fireEvent.click(screen.getByRole('checkbox'));expect(screen.getByRole('button',{name:'确认这组业务边界'})).toBeEnabled();view.rerender(<BoundaryProposalReview {...p} proposalView={{...d,proposal:{...d.proposal,proposal_id:'p2'}}}/>);expect(screen.getByRole('button',{name:'确认这组业务边界'})).toBeDisabled();expect(p.onApprove).not.toHaveBeenCalled()})
